// Generated by jextract

package vulkan;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c:
 * typedef void (*PFN_vkCmdWriteTimestamp2KHR)(VkCommandBuffer, VkPipelineStageFlags2, VkQueryPool, uint32_t) __attribute__((stdcall))
 *}
 */
public final class PFN_vkCmdWriteTimestamp2KHR
{

	private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
			Vulkan.C_POINTER,
			Vulkan.C_LONG_LONG,
			Vulkan.C_POINTER,
			Vulkan.C_INT
	);
	private static final MethodHandle UP$MH =
			Vulkan.upcallHandle(PFN_vkCmdWriteTimestamp2KHR.Function.class, "apply", $DESC);
	private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

	private PFN_vkCmdWriteTimestamp2KHR()
	{
		// Should not be called directly
	}

	/**
	 * The descriptor of this function pointer
	 */
	public static FunctionDescriptor descriptor()
	{
		return $DESC;
	}

	/**
	 * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
	 * is managed by {@code arena}
	 */
	public static MemorySegment allocate(PFN_vkCmdWriteTimestamp2KHR.Function fi, Arena arena)
	{
		return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
	}

	/**
	 * Invoke the upcall stub {@code funcPtr}, with given parameters
	 */
	public static void invoke(MemorySegment funcPtr, MemorySegment commandBuffer, long stage, MemorySegment queryPool,
							  int query)
	{
		try
		{
			DOWN$MH.invokeExact(funcPtr, commandBuffer, stage, queryPool, query);
		} catch (Error | RuntimeException ex)
		{
			throw ex;
		} catch (Throwable ex$)
		{
			throw new AssertionError("should not reach here", ex$);
		}
	}

	/**
	 * The function pointer signature, expressed as a functional interface
	 */
	public interface Function
	{
		void apply(MemorySegment commandBuffer, long stage, MemorySegment queryPool, int query);
	}
}

