// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang = c:
 * struct VkAccelerationStructureBuildSizesInfoKHR {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkDeviceSize accelerationStructureSize;
 *     VkDeviceSize updateScratchSize;
 *     VkDeviceSize buildScratchSize;
 * }
 *}
 */
public class VkAccelerationStructureBuildSizesInfoKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_LONG_LONG.withName("accelerationStructureSize"),
			Vulkan.C_LONG_LONG.withName("updateScratchSize"),
			Vulkan.C_LONG_LONG.withName("buildScratchSize")
	).withName("VkAccelerationStructureBuildSizesInfoKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfLong accelerationStructureSize$LAYOUT =
			(OfLong) $LAYOUT.select(groupElement("accelerationStructureSize"));
	private static final long accelerationStructureSize$OFFSET =
			$LAYOUT.byteOffset(groupElement("accelerationStructureSize"));
	private static final OfLong updateScratchSize$LAYOUT = (OfLong) $LAYOUT.select(groupElement("updateScratchSize"));
	private static final long updateScratchSize$OFFSET = $LAYOUT.byteOffset(groupElement("updateScratchSize"));
	private static final OfLong buildScratchSize$LAYOUT = (OfLong) $LAYOUT.select(groupElement("buildScratchSize"));
	private static final long buildScratchSize$OFFSET = $LAYOUT.byteOffset(groupElement("buildScratchSize"));

	VkAccelerationStructureBuildSizesInfoKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkDeviceSize accelerationStructureSize
	 *}
	 */
	public static final OfLong accelerationStructureSize$layout()
	{
		return accelerationStructureSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkDeviceSize accelerationStructureSize
	 *}
	 */
	public static final long accelerationStructureSize$offset()
	{
		return accelerationStructureSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize accelerationStructureSize
	 *}
	 */
	public static long accelerationStructureSize(MemorySegment struct)
	{
		return struct.get(accelerationStructureSize$LAYOUT, accelerationStructureSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize accelerationStructureSize
	 *}
	 */
	public static void accelerationStructureSize(MemorySegment struct, long fieldValue)
	{
		struct.set(accelerationStructureSize$LAYOUT, accelerationStructureSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkDeviceSize updateScratchSize
	 *}
	 */
	public static final OfLong updateScratchSize$layout()
	{
		return updateScratchSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkDeviceSize updateScratchSize
	 *}
	 */
	public static final long updateScratchSize$offset()
	{
		return updateScratchSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize updateScratchSize
	 *}
	 */
	public static long updateScratchSize(MemorySegment struct)
	{
		return struct.get(updateScratchSize$LAYOUT, updateScratchSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize updateScratchSize
	 *}
	 */
	public static void updateScratchSize(MemorySegment struct, long fieldValue)
	{
		struct.set(updateScratchSize$LAYOUT, updateScratchSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkDeviceSize buildScratchSize
	 *}
	 */
	public static final OfLong buildScratchSize$layout()
	{
		return buildScratchSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkDeviceSize buildScratchSize
	 *}
	 */
	public static final long buildScratchSize$offset()
	{
		return buildScratchSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize buildScratchSize
	 *}
	 */
	public static long buildScratchSize(MemorySegment struct)
	{
		return struct.get(buildScratchSize$LAYOUT, buildScratchSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkDeviceSize buildScratchSize
	 *}
	 */
	public static void buildScratchSize(MemorySegment struct, long fieldValue)
	{
		struct.set(buildScratchSize$LAYOUT, buildScratchSize$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

