// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkAttachmentReference2 VkAttachmentReference2KHR
 *}
 */
public class VkAttachmentReference2KHR extends VkAttachmentReference2
{

	VkAttachmentReference2KHR()
	{
		// Should not be called directly
	}
}

