// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkBindSparseInfo {
 *     VkStructureType sType;
 *     const void *pNext;
 *     uint32_t waitSemaphoreCount;
 *     const VkSemaphore *pWaitSemaphores;
 *     uint32_t bufferBindCount;
 *     const VkSparseBufferMemoryBindInfo *pBufferBinds;
 *     uint32_t imageOpaqueBindCount;
 *     const VkSparseImageOpaqueMemoryBindInfo *pImageOpaqueBinds;
 *     uint32_t imageBindCount;
 *     const VkSparseImageMemoryBindInfo *pImageBinds;
 *     uint32_t signalSemaphoreCount;
 *     const VkSemaphore *pSignalSemaphores;
 * }
 *}
 */
public class VkBindSparseInfo
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("waitSemaphoreCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pWaitSemaphores"),
			Vulkan.C_INT.withName("bufferBindCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pBufferBinds"),
			Vulkan.C_INT.withName("imageOpaqueBindCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pImageOpaqueBinds"),
			Vulkan.C_INT.withName("imageBindCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pImageBinds"),
			Vulkan.C_INT.withName("signalSemaphoreCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pSignalSemaphores")
	).withName("VkBindSparseInfo");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt waitSemaphoreCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("waitSemaphoreCount"));
	private static final long waitSemaphoreCount$OFFSET = $LAYOUT.byteOffset(groupElement("waitSemaphoreCount"));
	private static final AddressLayout pWaitSemaphores$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pWaitSemaphores"));
	private static final long pWaitSemaphores$OFFSET = $LAYOUT.byteOffset(groupElement("pWaitSemaphores"));
	private static final OfInt bufferBindCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("bufferBindCount"));
	private static final long bufferBindCount$OFFSET = $LAYOUT.byteOffset(groupElement("bufferBindCount"));
	private static final AddressLayout pBufferBinds$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pBufferBinds"));
	private static final long pBufferBinds$OFFSET = $LAYOUT.byteOffset(groupElement("pBufferBinds"));
	private static final OfInt imageOpaqueBindCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("imageOpaqueBindCount"));
	private static final long imageOpaqueBindCount$OFFSET = $LAYOUT.byteOffset(groupElement("imageOpaqueBindCount"));
	private static final AddressLayout pImageOpaqueBinds$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pImageOpaqueBinds"));
	private static final long pImageOpaqueBinds$OFFSET = $LAYOUT.byteOffset(groupElement("pImageOpaqueBinds"));
	private static final OfInt imageBindCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("imageBindCount"));
	private static final long imageBindCount$OFFSET = $LAYOUT.byteOffset(groupElement("imageBindCount"));
	private static final AddressLayout pImageBinds$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pImageBinds"));
	private static final long pImageBinds$OFFSET = $LAYOUT.byteOffset(groupElement("pImageBinds"));
	private static final OfInt signalSemaphoreCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("signalSemaphoreCount"));
	private static final long signalSemaphoreCount$OFFSET = $LAYOUT.byteOffset(groupElement("signalSemaphoreCount"));
	private static final AddressLayout pSignalSemaphores$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pSignalSemaphores"));
	private static final long pSignalSemaphores$OFFSET = $LAYOUT.byteOffset(groupElement("pSignalSemaphores"));

	VkBindSparseInfo()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t waitSemaphoreCount
	 *}
	 */
	public static final OfInt waitSemaphoreCount$layout()
	{
		return waitSemaphoreCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t waitSemaphoreCount
	 *}
	 */
	public static final long waitSemaphoreCount$offset()
	{
		return waitSemaphoreCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t waitSemaphoreCount
	 *}
	 */
	public static int waitSemaphoreCount(MemorySegment struct)
	{
		return struct.get(waitSemaphoreCount$LAYOUT, waitSemaphoreCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t waitSemaphoreCount
	 *}
	 */
	public static void waitSemaphoreCount(MemorySegment struct, int fieldValue)
	{
		struct.set(waitSemaphoreCount$LAYOUT, waitSemaphoreCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pWaitSemaphores
	 *}
	 */
	public static final AddressLayout pWaitSemaphores$layout()
	{
		return pWaitSemaphores$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pWaitSemaphores
	 *}
	 */
	public static final long pWaitSemaphores$offset()
	{
		return pWaitSemaphores$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pWaitSemaphores
	 *}
	 */
	public static MemorySegment pWaitSemaphores(MemorySegment struct)
	{
		return struct.get(pWaitSemaphores$LAYOUT, pWaitSemaphores$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pWaitSemaphores
	 *}
	 */
	public static void pWaitSemaphores(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pWaitSemaphores$LAYOUT, pWaitSemaphores$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t bufferBindCount
	 *}
	 */
	public static final OfInt bufferBindCount$layout()
	{
		return bufferBindCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t bufferBindCount
	 *}
	 */
	public static final long bufferBindCount$offset()
	{
		return bufferBindCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t bufferBindCount
	 *}
	 */
	public static int bufferBindCount(MemorySegment struct)
	{
		return struct.get(bufferBindCount$LAYOUT, bufferBindCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t bufferBindCount
	 *}
	 */
	public static void bufferBindCount(MemorySegment struct, int fieldValue)
	{
		struct.set(bufferBindCount$LAYOUT, bufferBindCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkSparseBufferMemoryBindInfo *pBufferBinds
	 *}
	 */
	public static final AddressLayout pBufferBinds$layout()
	{
		return pBufferBinds$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkSparseBufferMemoryBindInfo *pBufferBinds
	 *}
	 */
	public static final long pBufferBinds$offset()
	{
		return pBufferBinds$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkSparseBufferMemoryBindInfo *pBufferBinds
	 *}
	 */
	public static MemorySegment pBufferBinds(MemorySegment struct)
	{
		return struct.get(pBufferBinds$LAYOUT, pBufferBinds$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkSparseBufferMemoryBindInfo *pBufferBinds
	 *}
	 */
	public static void pBufferBinds(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pBufferBinds$LAYOUT, pBufferBinds$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t imageOpaqueBindCount
	 *}
	 */
	public static final OfInt imageOpaqueBindCount$layout()
	{
		return imageOpaqueBindCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t imageOpaqueBindCount
	 *}
	 */
	public static final long imageOpaqueBindCount$offset()
	{
		return imageOpaqueBindCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t imageOpaqueBindCount
	 *}
	 */
	public static int imageOpaqueBindCount(MemorySegment struct)
	{
		return struct.get(imageOpaqueBindCount$LAYOUT, imageOpaqueBindCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t imageOpaqueBindCount
	 *}
	 */
	public static void imageOpaqueBindCount(MemorySegment struct, int fieldValue)
	{
		struct.set(imageOpaqueBindCount$LAYOUT, imageOpaqueBindCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkSparseImageOpaqueMemoryBindInfo *pImageOpaqueBinds
	 *}
	 */
	public static final AddressLayout pImageOpaqueBinds$layout()
	{
		return pImageOpaqueBinds$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkSparseImageOpaqueMemoryBindInfo *pImageOpaqueBinds
	 *}
	 */
	public static final long pImageOpaqueBinds$offset()
	{
		return pImageOpaqueBinds$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkSparseImageOpaqueMemoryBindInfo *pImageOpaqueBinds
	 *}
	 */
	public static MemorySegment pImageOpaqueBinds(MemorySegment struct)
	{
		return struct.get(pImageOpaqueBinds$LAYOUT, pImageOpaqueBinds$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkSparseImageOpaqueMemoryBindInfo *pImageOpaqueBinds
	 *}
	 */
	public static void pImageOpaqueBinds(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pImageOpaqueBinds$LAYOUT, pImageOpaqueBinds$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t imageBindCount
	 *}
	 */
	public static final OfInt imageBindCount$layout()
	{
		return imageBindCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t imageBindCount
	 *}
	 */
	public static final long imageBindCount$offset()
	{
		return imageBindCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t imageBindCount
	 *}
	 */
	public static int imageBindCount(MemorySegment struct)
	{
		return struct.get(imageBindCount$LAYOUT, imageBindCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t imageBindCount
	 *}
	 */
	public static void imageBindCount(MemorySegment struct, int fieldValue)
	{
		struct.set(imageBindCount$LAYOUT, imageBindCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkSparseImageMemoryBindInfo *pImageBinds
	 *}
	 */
	public static final AddressLayout pImageBinds$layout()
	{
		return pImageBinds$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkSparseImageMemoryBindInfo *pImageBinds
	 *}
	 */
	public static final long pImageBinds$offset()
	{
		return pImageBinds$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkSparseImageMemoryBindInfo *pImageBinds
	 *}
	 */
	public static MemorySegment pImageBinds(MemorySegment struct)
	{
		return struct.get(pImageBinds$LAYOUT, pImageBinds$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkSparseImageMemoryBindInfo *pImageBinds
	 *}
	 */
	public static void pImageBinds(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pImageBinds$LAYOUT, pImageBinds$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t signalSemaphoreCount
	 *}
	 */
	public static final OfInt signalSemaphoreCount$layout()
	{
		return signalSemaphoreCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t signalSemaphoreCount
	 *}
	 */
	public static final long signalSemaphoreCount$offset()
	{
		return signalSemaphoreCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t signalSemaphoreCount
	 *}
	 */
	public static int signalSemaphoreCount(MemorySegment struct)
	{
		return struct.get(signalSemaphoreCount$LAYOUT, signalSemaphoreCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t signalSemaphoreCount
	 *}
	 */
	public static void signalSemaphoreCount(MemorySegment struct, int fieldValue)
	{
		struct.set(signalSemaphoreCount$LAYOUT, signalSemaphoreCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pSignalSemaphores
	 *}
	 */
	public static final AddressLayout pSignalSemaphores$layout()
	{
		return pSignalSemaphores$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pSignalSemaphores
	 *}
	 */
	public static final long pSignalSemaphores$offset()
	{
		return pSignalSemaphores$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pSignalSemaphores
	 *}
	 */
	public static MemorySegment pSignalSemaphores(MemorySegment struct)
	{
		return struct.get(pSignalSemaphores$LAYOUT, pSignalSemaphores$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkSemaphore *pSignalSemaphores
	 *}
	 */
	public static void pSignalSemaphores(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pSignalSemaphores$LAYOUT, pSignalSemaphores$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

