// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkBufferImageCopy2 VkBufferImageCopy2KHR
 *}
 */
public class VkBufferImageCopy2KHR extends VkBufferImageCopy2
{

	VkBufferImageCopy2KHR()
	{
		// Should not be called directly
	}
}

