// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkClusterAccelerationStructureTriangleClusterInputNV {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkFormat vertexFormat;
 *     uint32_t maxGeometryIndexValue;
 *     uint32_t maxClusterUniqueGeometryCount;
 *     uint32_t maxClusterTriangleCount;
 *     uint32_t maxClusterVertexCount;
 *     uint32_t maxTotalTriangleCount;
 *     uint32_t maxTotalVertexCount;
 *     uint32_t minPositionTruncateBitCount;
 * }
 *}
 */
public class VkClusterAccelerationStructureTriangleClusterInputNV
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("vertexFormat"),
			Vulkan.C_INT.withName("maxGeometryIndexValue"),
			Vulkan.C_INT.withName("maxClusterUniqueGeometryCount"),
			Vulkan.C_INT.withName("maxClusterTriangleCount"),
			Vulkan.C_INT.withName("maxClusterVertexCount"),
			Vulkan.C_INT.withName("maxTotalTriangleCount"),
			Vulkan.C_INT.withName("maxTotalVertexCount"),
			Vulkan.C_INT.withName("minPositionTruncateBitCount")
	).withName("VkClusterAccelerationStructureTriangleClusterInputNV");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt vertexFormat$LAYOUT = (OfInt) $LAYOUT.select(groupElement("vertexFormat"));
	private static final long vertexFormat$OFFSET = $LAYOUT.byteOffset(groupElement("vertexFormat"));
	private static final OfInt maxGeometryIndexValue$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxGeometryIndexValue"));
	private static final long maxGeometryIndexValue$OFFSET = $LAYOUT.byteOffset(groupElement("maxGeometryIndexValue"));
	private static final OfInt maxClusterUniqueGeometryCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxClusterUniqueGeometryCount"));
	private static final long maxClusterUniqueGeometryCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxClusterUniqueGeometryCount"));
	private static final OfInt maxClusterTriangleCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxClusterTriangleCount"));
	private static final long maxClusterTriangleCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxClusterTriangleCount"));
	private static final OfInt maxClusterVertexCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxClusterVertexCount"));
	private static final long maxClusterVertexCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxClusterVertexCount"));
	private static final OfInt maxTotalTriangleCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxTotalTriangleCount"));
	private static final long maxTotalTriangleCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxTotalTriangleCount"));
	private static final OfInt maxTotalVertexCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("maxTotalVertexCount"));
	private static final long maxTotalVertexCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxTotalVertexCount"));
	private static final OfInt minPositionTruncateBitCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("minPositionTruncateBitCount"));
	private static final long minPositionTruncateBitCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("minPositionTruncateBitCount"));

	VkClusterAccelerationStructureTriangleClusterInputNV()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkFormat vertexFormat
	 *}
	 */
	public static final OfInt vertexFormat$layout()
	{
		return vertexFormat$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkFormat vertexFormat
	 *}
	 */
	public static final long vertexFormat$offset()
	{
		return vertexFormat$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkFormat vertexFormat
	 *}
	 */
	public static int vertexFormat(MemorySegment struct)
	{
		return struct.get(vertexFormat$LAYOUT, vertexFormat$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkFormat vertexFormat
	 *}
	 */
	public static void vertexFormat(MemorySegment struct, int fieldValue)
	{
		struct.set(vertexFormat$LAYOUT, vertexFormat$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxGeometryIndexValue
	 *}
	 */
	public static final OfInt maxGeometryIndexValue$layout()
	{
		return maxGeometryIndexValue$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxGeometryIndexValue
	 *}
	 */
	public static final long maxGeometryIndexValue$offset()
	{
		return maxGeometryIndexValue$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxGeometryIndexValue
	 *}
	 */
	public static int maxGeometryIndexValue(MemorySegment struct)
	{
		return struct.get(maxGeometryIndexValue$LAYOUT, maxGeometryIndexValue$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxGeometryIndexValue
	 *}
	 */
	public static void maxGeometryIndexValue(MemorySegment struct, int fieldValue)
	{
		struct.set(maxGeometryIndexValue$LAYOUT, maxGeometryIndexValue$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterUniqueGeometryCount
	 *}
	 */
	public static final OfInt maxClusterUniqueGeometryCount$layout()
	{
		return maxClusterUniqueGeometryCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterUniqueGeometryCount
	 *}
	 */
	public static final long maxClusterUniqueGeometryCount$offset()
	{
		return maxClusterUniqueGeometryCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterUniqueGeometryCount
	 *}
	 */
	public static int maxClusterUniqueGeometryCount(MemorySegment struct)
	{
		return struct.get(maxClusterUniqueGeometryCount$LAYOUT, maxClusterUniqueGeometryCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterUniqueGeometryCount
	 *}
	 */
	public static void maxClusterUniqueGeometryCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxClusterUniqueGeometryCount$LAYOUT, maxClusterUniqueGeometryCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterTriangleCount
	 *}
	 */
	public static final OfInt maxClusterTriangleCount$layout()
	{
		return maxClusterTriangleCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterTriangleCount
	 *}
	 */
	public static final long maxClusterTriangleCount$offset()
	{
		return maxClusterTriangleCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterTriangleCount
	 *}
	 */
	public static int maxClusterTriangleCount(MemorySegment struct)
	{
		return struct.get(maxClusterTriangleCount$LAYOUT, maxClusterTriangleCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterTriangleCount
	 *}
	 */
	public static void maxClusterTriangleCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxClusterTriangleCount$LAYOUT, maxClusterTriangleCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterVertexCount
	 *}
	 */
	public static final OfInt maxClusterVertexCount$layout()
	{
		return maxClusterVertexCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterVertexCount
	 *}
	 */
	public static final long maxClusterVertexCount$offset()
	{
		return maxClusterVertexCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterVertexCount
	 *}
	 */
	public static int maxClusterVertexCount(MemorySegment struct)
	{
		return struct.get(maxClusterVertexCount$LAYOUT, maxClusterVertexCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxClusterVertexCount
	 *}
	 */
	public static void maxClusterVertexCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxClusterVertexCount$LAYOUT, maxClusterVertexCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalTriangleCount
	 *}
	 */
	public static final OfInt maxTotalTriangleCount$layout()
	{
		return maxTotalTriangleCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalTriangleCount
	 *}
	 */
	public static final long maxTotalTriangleCount$offset()
	{
		return maxTotalTriangleCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalTriangleCount
	 *}
	 */
	public static int maxTotalTriangleCount(MemorySegment struct)
	{
		return struct.get(maxTotalTriangleCount$LAYOUT, maxTotalTriangleCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalTriangleCount
	 *}
	 */
	public static void maxTotalTriangleCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxTotalTriangleCount$LAYOUT, maxTotalTriangleCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalVertexCount
	 *}
	 */
	public static final OfInt maxTotalVertexCount$layout()
	{
		return maxTotalVertexCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalVertexCount
	 *}
	 */
	public static final long maxTotalVertexCount$offset()
	{
		return maxTotalVertexCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalVertexCount
	 *}
	 */
	public static int maxTotalVertexCount(MemorySegment struct)
	{
		return struct.get(maxTotalVertexCount$LAYOUT, maxTotalVertexCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTotalVertexCount
	 *}
	 */
	public static void maxTotalVertexCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxTotalVertexCount$LAYOUT, maxTotalVertexCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t minPositionTruncateBitCount
	 *}
	 */
	public static final OfInt minPositionTruncateBitCount$layout()
	{
		return minPositionTruncateBitCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t minPositionTruncateBitCount
	 *}
	 */
	public static final long minPositionTruncateBitCount$offset()
	{
		return minPositionTruncateBitCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t minPositionTruncateBitCount
	 *}
	 */
	public static int minPositionTruncateBitCount(MemorySegment struct)
	{
		return struct.get(minPositionTruncateBitCount$LAYOUT, minPositionTruncateBitCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t minPositionTruncateBitCount
	 *}
	 */
	public static void minPositionTruncateBitCount(MemorySegment struct, int fieldValue)
	{
		struct.set(minPositionTruncateBitCount$LAYOUT, minPositionTruncateBitCount$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

