// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkCommandBufferInheritanceViewportScissorInfoNV {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkBool32 viewportScissor2D;
 *     uint32_t viewportDepthCount;
 *     const VkViewport *pViewportDepths;
 * }
 *}
 */
public class VkCommandBufferInheritanceViewportScissorInfoNV
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("viewportScissor2D"),
			Vulkan.C_INT.withName("viewportDepthCount"),
			Vulkan.C_POINTER.withName("pViewportDepths")
	).withName("VkCommandBufferInheritanceViewportScissorInfoNV");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt viewportScissor2D$LAYOUT = (OfInt) $LAYOUT.select(groupElement("viewportScissor2D"));
	private static final long viewportScissor2D$OFFSET = $LAYOUT.byteOffset(groupElement("viewportScissor2D"));
	private static final OfInt viewportDepthCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("viewportDepthCount"));
	private static final long viewportDepthCount$OFFSET = $LAYOUT.byteOffset(groupElement("viewportDepthCount"));
	private static final AddressLayout pViewportDepths$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pViewportDepths"));
	private static final long pViewportDepths$OFFSET = $LAYOUT.byteOffset(groupElement("pViewportDepths"));

	VkCommandBufferInheritanceViewportScissorInfoNV()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 viewportScissor2D
	 *}
	 */
	public static final OfInt viewportScissor2D$layout()
	{
		return viewportScissor2D$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 viewportScissor2D
	 *}
	 */
	public static final long viewportScissor2D$offset()
	{
		return viewportScissor2D$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 viewportScissor2D
	 *}
	 */
	public static int viewportScissor2D(MemorySegment struct)
	{
		return struct.get(viewportScissor2D$LAYOUT, viewportScissor2D$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 viewportScissor2D
	 *}
	 */
	public static void viewportScissor2D(MemorySegment struct, int fieldValue)
	{
		struct.set(viewportScissor2D$LAYOUT, viewportScissor2D$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t viewportDepthCount
	 *}
	 */
	public static final OfInt viewportDepthCount$layout()
	{
		return viewportDepthCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t viewportDepthCount
	 *}
	 */
	public static final long viewportDepthCount$offset()
	{
		return viewportDepthCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t viewportDepthCount
	 *}
	 */
	public static int viewportDepthCount(MemorySegment struct)
	{
		return struct.get(viewportDepthCount$LAYOUT, viewportDepthCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t viewportDepthCount
	 *}
	 */
	public static void viewportDepthCount(MemorySegment struct, int fieldValue)
	{
		struct.set(viewportDepthCount$LAYOUT, viewportDepthCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkViewport *pViewportDepths
	 *}
	 */
	public static final AddressLayout pViewportDepths$layout()
	{
		return pViewportDepths$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkViewport *pViewportDepths
	 *}
	 */
	public static final long pViewportDepths$offset()
	{
		return pViewportDepths$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkViewport *pViewportDepths
	 *}
	 */
	public static MemorySegment pViewportDepths(MemorySegment struct)
	{
		return struct.get(pViewportDepths$LAYOUT, pViewportDepths$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkViewport *pViewportDepths
	 *}
	 */
	public static void pViewportDepths(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pViewportDepths$LAYOUT, pViewportDepths$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

