// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.MemoryLayout.PathElement.sequenceElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkDeviceGroupPresentCapabilitiesKHR {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t presentMask[32];
 *     VkDeviceGroupPresentModeFlagsKHR modes;
 * }
 *}
 */
public class VkDeviceGroupPresentCapabilitiesKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			MemoryLayout.sequenceLayout(32, Vulkan.C_INT).withName("presentMask"),
			Vulkan.C_INT.withName("modes"),
			MemoryLayout.paddingLayout(4)
	).withName("VkDeviceGroupPresentCapabilitiesKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final SequenceLayout presentMask$LAYOUT =
			(SequenceLayout) $LAYOUT.select(groupElement("presentMask"));
	private static final VarHandle presentMask$ELEM_HANDLE = presentMask$LAYOUT.varHandle(sequenceElement());
	private static final long presentMask$OFFSET = $LAYOUT.byteOffset(groupElement("presentMask"));
	private static final OfInt modes$LAYOUT = (OfInt) $LAYOUT.select(groupElement("modes"));
	private static final long modes$OFFSET = $LAYOUT.byteOffset(groupElement("modes"));
	private static long[] presentMask$DIMS = {32};

	VkDeviceGroupPresentCapabilitiesKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static final SequenceLayout presentMask$layout()
	{
		return presentMask$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static final long presentMask$offset()
	{
		return presentMask$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static MemorySegment presentMask(MemorySegment struct)
	{
		return struct.asSlice(presentMask$OFFSET, presentMask$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static void presentMask(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, presentMask$OFFSET, presentMask$LAYOUT.byteSize());
	}

	/**
	 * Dimensions for array field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static long[] presentMask$dimensions()
	{
		return presentMask$DIMS;
	}

	/**
	 * Indexed getter for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static int presentMask(MemorySegment struct, long index0)
	{
		return (int) presentMask$ELEM_HANDLE.get(struct, presentMask$OFFSET, index0);
	}

	/**
	 * Indexed setter for field:
	 * {@snippet lang = c:
	 * uint32_t presentMask[32]
	 *}
	 */
	public static void presentMask(MemorySegment struct, long index0, int fieldValue)
	{
		presentMask$ELEM_HANDLE.set(struct, presentMask$OFFSET, index0, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkDeviceGroupPresentModeFlagsKHR modes
	 *}
	 */
	public static final OfInt modes$layout()
	{
		return modes$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkDeviceGroupPresentModeFlagsKHR modes
	 *}
	 */
	public static final long modes$offset()
	{
		return modes$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkDeviceGroupPresentModeFlagsKHR modes
	 *}
	 */
	public static int modes(MemorySegment struct)
	{
		return struct.get(modes$LAYOUT, modes$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkDeviceGroupPresentModeFlagsKHR modes
	 *}
	 */
	public static void modes(MemorySegment struct, int fieldValue)
	{
		struct.set(modes$LAYOUT, modes$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

