// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkDeviceImageSubresourceInfo VkDeviceImageSubresourceInfoKHR
 *}
 */
public class VkDeviceImageSubresourceInfoKHR extends VkDeviceImageSubresourceInfo
{

	VkDeviceImageSubresourceInfoKHR()
	{
		// Should not be called directly
	}
}

