// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkDeviceGroupRenderPassBeginInfo VkDeviceGroupRenderPassBeginInfoKHR
 *}
 */
public class VkDeviceGroupRenderPassBeginInfoKHR extends VkDeviceGroupRenderPassBeginInfo
{

	VkDeviceGroupRenderPassBeginInfoKHR()
	{
		// Should not be called directly
	}
}

