// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkGeneratedCommandsMemoryRequirementsInfoNV {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkPipelineBindPoint pipelineBindPoint;
 *     VkPipeline pipeline;
 *     VkIndirectCommandsLayoutNV indirectCommandsLayout;
 *     uint32_t maxSequencesCount;
 * }
 *}
 */
public class VkGeneratedCommandsMemoryRequirementsInfoNV
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("pipelineBindPoint"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pipeline"),
			Vulkan.C_POINTER.withName("indirectCommandsLayout"),
			Vulkan.C_INT.withName("maxSequencesCount"),
			MemoryLayout.paddingLayout(4)
	).withName("VkGeneratedCommandsMemoryRequirementsInfoNV");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt pipelineBindPoint$LAYOUT = (OfInt) $LAYOUT.select(groupElement("pipelineBindPoint"));
	private static final long pipelineBindPoint$OFFSET = $LAYOUT.byteOffset(groupElement("pipelineBindPoint"));
	private static final AddressLayout pipeline$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pipeline"));
	private static final long pipeline$OFFSET = $LAYOUT.byteOffset(groupElement("pipeline"));
	private static final AddressLayout indirectCommandsLayout$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("indirectCommandsLayout"));
	private static final long indirectCommandsLayout$OFFSET =
			$LAYOUT.byteOffset(groupElement("indirectCommandsLayout"));
	private static final OfInt maxSequencesCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("maxSequencesCount"));
	private static final long maxSequencesCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxSequencesCount"));

	VkGeneratedCommandsMemoryRequirementsInfoNV()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkPipelineBindPoint pipelineBindPoint
	 *}
	 */
	public static final OfInt pipelineBindPoint$layout()
	{
		return pipelineBindPoint$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkPipelineBindPoint pipelineBindPoint
	 *}
	 */
	public static final long pipelineBindPoint$offset()
	{
		return pipelineBindPoint$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkPipelineBindPoint pipelineBindPoint
	 *}
	 */
	public static int pipelineBindPoint(MemorySegment struct)
	{
		return struct.get(pipelineBindPoint$LAYOUT, pipelineBindPoint$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkPipelineBindPoint pipelineBindPoint
	 *}
	 */
	public static void pipelineBindPoint(MemorySegment struct, int fieldValue)
	{
		struct.set(pipelineBindPoint$LAYOUT, pipelineBindPoint$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkPipeline pipeline
	 *}
	 */
	public static final AddressLayout pipeline$layout()
	{
		return pipeline$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkPipeline pipeline
	 *}
	 */
	public static final long pipeline$offset()
	{
		return pipeline$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkPipeline pipeline
	 *}
	 */
	public static MemorySegment pipeline(MemorySegment struct)
	{
		return struct.get(pipeline$LAYOUT, pipeline$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkPipeline pipeline
	 *}
	 */
	public static void pipeline(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pipeline$LAYOUT, pipeline$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkIndirectCommandsLayoutNV indirectCommandsLayout
	 *}
	 */
	public static final AddressLayout indirectCommandsLayout$layout()
	{
		return indirectCommandsLayout$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkIndirectCommandsLayoutNV indirectCommandsLayout
	 *}
	 */
	public static final long indirectCommandsLayout$offset()
	{
		return indirectCommandsLayout$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkIndirectCommandsLayoutNV indirectCommandsLayout
	 *}
	 */
	public static MemorySegment indirectCommandsLayout(MemorySegment struct)
	{
		return struct.get(indirectCommandsLayout$LAYOUT, indirectCommandsLayout$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkIndirectCommandsLayoutNV indirectCommandsLayout
	 *}
	 */
	public static void indirectCommandsLayout(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(indirectCommandsLayout$LAYOUT, indirectCommandsLayout$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxSequencesCount
	 *}
	 */
	public static final OfInt maxSequencesCount$layout()
	{
		return maxSequencesCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxSequencesCount
	 *}
	 */
	public static final long maxSequencesCount$offset()
	{
		return maxSequencesCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxSequencesCount
	 *}
	 */
	public static int maxSequencesCount(MemorySegment struct)
	{
		return struct.get(maxSequencesCount$LAYOUT, maxSequencesCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxSequencesCount
	 *}
	 */
	public static void maxSequencesCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxSequencesCount$LAYOUT, maxSequencesCount$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

