// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkImageCompressionControlEXT {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkImageCompressionFlagsEXT flags;
 *     uint32_t compressionControlPlaneCount;
 *     VkImageCompressionFixedRateFlagsEXT *pFixedRateFlags;
 * }
 *}
 */
public class VkImageCompressionControlEXT
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("flags"),
			Vulkan.C_INT.withName("compressionControlPlaneCount"),
			Vulkan.C_POINTER.withName("pFixedRateFlags")
	).withName("VkImageCompressionControlEXT");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt flags$LAYOUT = (OfInt) $LAYOUT.select(groupElement("flags"));
	private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));
	private static final OfInt compressionControlPlaneCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("compressionControlPlaneCount"));
	private static final long compressionControlPlaneCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("compressionControlPlaneCount"));
	private static final AddressLayout pFixedRateFlags$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pFixedRateFlags"));
	private static final long pFixedRateFlags$OFFSET = $LAYOUT.byteOffset(groupElement("pFixedRateFlags"));

	VkImageCompressionControlEXT()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFlagsEXT flags
	 *}
	 */
	public static final OfInt flags$layout()
	{
		return flags$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFlagsEXT flags
	 *}
	 */
	public static final long flags$offset()
	{
		return flags$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFlagsEXT flags
	 *}
	 */
	public static int flags(MemorySegment struct)
	{
		return struct.get(flags$LAYOUT, flags$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFlagsEXT flags
	 *}
	 */
	public static void flags(MemorySegment struct, int fieldValue)
	{
		struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t compressionControlPlaneCount
	 *}
	 */
	public static final OfInt compressionControlPlaneCount$layout()
	{
		return compressionControlPlaneCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t compressionControlPlaneCount
	 *}
	 */
	public static final long compressionControlPlaneCount$offset()
	{
		return compressionControlPlaneCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t compressionControlPlaneCount
	 *}
	 */
	public static int compressionControlPlaneCount(MemorySegment struct)
	{
		return struct.get(compressionControlPlaneCount$LAYOUT, compressionControlPlaneCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t compressionControlPlaneCount
	 *}
	 */
	public static void compressionControlPlaneCount(MemorySegment struct, int fieldValue)
	{
		struct.set(compressionControlPlaneCount$LAYOUT, compressionControlPlaneCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFixedRateFlagsEXT *pFixedRateFlags
	 *}
	 */
	public static final AddressLayout pFixedRateFlags$layout()
	{
		return pFixedRateFlags$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFixedRateFlagsEXT *pFixedRateFlags
	 *}
	 */
	public static final long pFixedRateFlags$offset()
	{
		return pFixedRateFlags$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFixedRateFlagsEXT *pFixedRateFlags
	 *}
	 */
	public static MemorySegment pFixedRateFlags(MemorySegment struct)
	{
		return struct.get(pFixedRateFlags$LAYOUT, pFixedRateFlags$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkImageCompressionFixedRateFlagsEXT *pFixedRateFlags
	 *}
	 */
	public static void pFixedRateFlags(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pFixedRateFlags$LAYOUT, pFixedRateFlags$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

