// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDeviceSubgroupSizeControlFeatures VkPhysicalDeviceSubgroupSizeControlFeaturesEXT
 *}
 */
public class VkPhysicalDeviceSubgroupSizeControlFeaturesEXT extends VkPhysicalDeviceSubgroupSizeControlFeatures
{

	VkPhysicalDeviceSubgroupSizeControlFeaturesEXT()
	{
		// Should not be called directly
	}
}

