// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV
 *}
 */
public class VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV
		extends VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR
{

	VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV()
	{
		// Should not be called directly
	}
}

