// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT VkPhysicalDeviceMutableDescriptorTypeFeaturesVALVE
 *}
 */
public class VkPhysicalDeviceMutableDescriptorTypeFeaturesVALVE extends VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT
{

	VkPhysicalDeviceMutableDescriptorTypeFeaturesVALVE()
	{
		// Should not be called directly
	}
}

