// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDeviceVulkan12Features {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkBool32 samplerMirrorClampToEdge;
 *     VkBool32 drawIndirectCount;
 *     VkBool32 storageBuffer8BitAccess;
 *     VkBool32 uniformAndStorageBuffer8BitAccess;
 *     VkBool32 storagePushConstant8;
 *     VkBool32 shaderBufferInt64Atomics;
 *     VkBool32 shaderSharedInt64Atomics;
 *     VkBool32 shaderFloat16;
 *     VkBool32 shaderInt8;
 *     VkBool32 descriptorIndexing;
 *     VkBool32 shaderInputAttachmentArrayDynamicIndexing;
 *     VkBool32 shaderUniformTexelBufferArrayDynamicIndexing;
 *     VkBool32 shaderStorageTexelBufferArrayDynamicIndexing;
 *     VkBool32 shaderUniformBufferArrayNonUniformIndexing;
 *     VkBool32 shaderSampledImageArrayNonUniformIndexing;
 *     VkBool32 shaderStorageBufferArrayNonUniformIndexing;
 *     VkBool32 shaderStorageImageArrayNonUniformIndexing;
 *     VkBool32 shaderInputAttachmentArrayNonUniformIndexing;
 *     VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing;
 *     VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing;
 *     VkBool32 descriptorBindingUniformBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingSampledImageUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageImageUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingUpdateUnusedWhilePending;
 *     VkBool32 descriptorBindingPartiallyBound;
 *     VkBool32 descriptorBindingVariableDescriptorCount;
 *     VkBool32 runtimeDescriptorArray;
 *     VkBool32 samplerFilterMinmax;
 *     VkBool32 scalarBlockLayout;
 *     VkBool32 imagelessFramebuffer;
 *     VkBool32 uniformBufferStandardLayout;
 *     VkBool32 shaderSubgroupExtendedTypes;
 *     VkBool32 separateDepthStencilLayouts;
 *     VkBool32 hostQueryReset;
 *     VkBool32 timelineSemaphore;
 *     VkBool32 bufferDeviceAddress;
 *     VkBool32 bufferDeviceAddressCaptureReplay;
 *     VkBool32 bufferDeviceAddressMultiDevice;
 *     VkBool32 vulkanMemoryModel;
 *     VkBool32 vulkanMemoryModelDeviceScope;
 *     VkBool32 vulkanMemoryModelAvailabilityVisibilityChains;
 *     VkBool32 shaderOutputViewportIndex;
 *     VkBool32 shaderOutputLayer;
 *     VkBool32 subgroupBroadcastDynamicId;
 * }
 *}
 */
public class VkPhysicalDeviceVulkan12Features
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("samplerMirrorClampToEdge"),
			Vulkan.C_INT.withName("drawIndirectCount"),
			Vulkan.C_INT.withName("storageBuffer8BitAccess"),
			Vulkan.C_INT.withName("uniformAndStorageBuffer8BitAccess"),
			Vulkan.C_INT.withName("storagePushConstant8"),
			Vulkan.C_INT.withName("shaderBufferInt64Atomics"),
			Vulkan.C_INT.withName("shaderSharedInt64Atomics"),
			Vulkan.C_INT.withName("shaderFloat16"),
			Vulkan.C_INT.withName("shaderInt8"),
			Vulkan.C_INT.withName("descriptorIndexing"),
			Vulkan.C_INT.withName("shaderInputAttachmentArrayDynamicIndexing"),
			Vulkan.C_INT.withName("shaderUniformTexelBufferArrayDynamicIndexing"),
			Vulkan.C_INT.withName("shaderStorageTexelBufferArrayDynamicIndexing"),
			Vulkan.C_INT.withName("shaderUniformBufferArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderSampledImageArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderStorageBufferArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderStorageImageArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderInputAttachmentArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderUniformTexelBufferArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("shaderStorageTexelBufferArrayNonUniformIndexing"),
			Vulkan.C_INT.withName("descriptorBindingUniformBufferUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingSampledImageUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingStorageImageUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingStorageBufferUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingUniformTexelBufferUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingStorageTexelBufferUpdateAfterBind"),
			Vulkan.C_INT.withName("descriptorBindingUpdateUnusedWhilePending"),
			Vulkan.C_INT.withName("descriptorBindingPartiallyBound"),
			Vulkan.C_INT.withName("descriptorBindingVariableDescriptorCount"),
			Vulkan.C_INT.withName("runtimeDescriptorArray"),
			Vulkan.C_INT.withName("samplerFilterMinmax"),
			Vulkan.C_INT.withName("scalarBlockLayout"),
			Vulkan.C_INT.withName("imagelessFramebuffer"),
			Vulkan.C_INT.withName("uniformBufferStandardLayout"),
			Vulkan.C_INT.withName("shaderSubgroupExtendedTypes"),
			Vulkan.C_INT.withName("separateDepthStencilLayouts"),
			Vulkan.C_INT.withName("hostQueryReset"),
			Vulkan.C_INT.withName("timelineSemaphore"),
			Vulkan.C_INT.withName("bufferDeviceAddress"),
			Vulkan.C_INT.withName("bufferDeviceAddressCaptureReplay"),
			Vulkan.C_INT.withName("bufferDeviceAddressMultiDevice"),
			Vulkan.C_INT.withName("vulkanMemoryModel"),
			Vulkan.C_INT.withName("vulkanMemoryModelDeviceScope"),
			Vulkan.C_INT.withName("vulkanMemoryModelAvailabilityVisibilityChains"),
			Vulkan.C_INT.withName("shaderOutputViewportIndex"),
			Vulkan.C_INT.withName("shaderOutputLayer"),
			Vulkan.C_INT.withName("subgroupBroadcastDynamicId"),
			MemoryLayout.paddingLayout(4)
	).withName("VkPhysicalDeviceVulkan12Features");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt samplerMirrorClampToEdge$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("samplerMirrorClampToEdge"));
	private static final long samplerMirrorClampToEdge$OFFSET =
			$LAYOUT.byteOffset(groupElement("samplerMirrorClampToEdge"));
	private static final OfInt drawIndirectCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("drawIndirectCount"));
	private static final long drawIndirectCount$OFFSET = $LAYOUT.byteOffset(groupElement("drawIndirectCount"));
	private static final OfInt storageBuffer8BitAccess$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("storageBuffer8BitAccess"));
	private static final long storageBuffer8BitAccess$OFFSET =
			$LAYOUT.byteOffset(groupElement("storageBuffer8BitAccess"));
	private static final OfInt uniformAndStorageBuffer8BitAccess$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("uniformAndStorageBuffer8BitAccess"));
	private static final long uniformAndStorageBuffer8BitAccess$OFFSET =
			$LAYOUT.byteOffset(groupElement("uniformAndStorageBuffer8BitAccess"));
	private static final OfInt storagePushConstant8$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("storagePushConstant8"));
	private static final long storagePushConstant8$OFFSET = $LAYOUT.byteOffset(groupElement("storagePushConstant8"));
	private static final OfInt shaderBufferInt64Atomics$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderBufferInt64Atomics"));
	private static final long shaderBufferInt64Atomics$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderBufferInt64Atomics"));
	private static final OfInt shaderSharedInt64Atomics$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderSharedInt64Atomics"));
	private static final long shaderSharedInt64Atomics$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderSharedInt64Atomics"));
	private static final OfInt shaderFloat16$LAYOUT = (OfInt) $LAYOUT.select(groupElement("shaderFloat16"));
	private static final long shaderFloat16$OFFSET = $LAYOUT.byteOffset(groupElement("shaderFloat16"));
	private static final OfInt shaderInt8$LAYOUT = (OfInt) $LAYOUT.select(groupElement("shaderInt8"));
	private static final long shaderInt8$OFFSET = $LAYOUT.byteOffset(groupElement("shaderInt8"));
	private static final OfInt descriptorIndexing$LAYOUT = (OfInt) $LAYOUT.select(groupElement("descriptorIndexing"));
	private static final long descriptorIndexing$OFFSET = $LAYOUT.byteOffset(groupElement("descriptorIndexing"));
	private static final OfInt shaderInputAttachmentArrayDynamicIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderInputAttachmentArrayDynamicIndexing"));
	private static final long shaderInputAttachmentArrayDynamicIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderInputAttachmentArrayDynamicIndexing"));
	private static final OfInt shaderUniformTexelBufferArrayDynamicIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderUniformTexelBufferArrayDynamicIndexing"));
	private static final long shaderUniformTexelBufferArrayDynamicIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderUniformTexelBufferArrayDynamicIndexing"));
	private static final OfInt shaderStorageTexelBufferArrayDynamicIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderStorageTexelBufferArrayDynamicIndexing"));
	private static final long shaderStorageTexelBufferArrayDynamicIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderStorageTexelBufferArrayDynamicIndexing"));
	private static final OfInt shaderUniformBufferArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderUniformBufferArrayNonUniformIndexing"));
	private static final long shaderUniformBufferArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderUniformBufferArrayNonUniformIndexing"));
	private static final OfInt shaderSampledImageArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderSampledImageArrayNonUniformIndexing"));
	private static final long shaderSampledImageArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderSampledImageArrayNonUniformIndexing"));
	private static final OfInt shaderStorageBufferArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderStorageBufferArrayNonUniformIndexing"));
	private static final long shaderStorageBufferArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderStorageBufferArrayNonUniformIndexing"));
	private static final OfInt shaderStorageImageArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderStorageImageArrayNonUniformIndexing"));
	private static final long shaderStorageImageArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderStorageImageArrayNonUniformIndexing"));
	private static final OfInt shaderInputAttachmentArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderInputAttachmentArrayNonUniformIndexing"));
	private static final long shaderInputAttachmentArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderInputAttachmentArrayNonUniformIndexing"));
	private static final OfInt shaderUniformTexelBufferArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderUniformTexelBufferArrayNonUniformIndexing"));
	private static final long shaderUniformTexelBufferArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderUniformTexelBufferArrayNonUniformIndexing"));
	private static final OfInt shaderStorageTexelBufferArrayNonUniformIndexing$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderStorageTexelBufferArrayNonUniformIndexing"));
	private static final long shaderStorageTexelBufferArrayNonUniformIndexing$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderStorageTexelBufferArrayNonUniformIndexing"));
	private static final OfInt descriptorBindingUniformBufferUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingUniformBufferUpdateAfterBind"));
	private static final long descriptorBindingUniformBufferUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingUniformBufferUpdateAfterBind"));
	private static final OfInt descriptorBindingSampledImageUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingSampledImageUpdateAfterBind"));
	private static final long descriptorBindingSampledImageUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingSampledImageUpdateAfterBind"));
	private static final OfInt descriptorBindingStorageImageUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingStorageImageUpdateAfterBind"));
	private static final long descriptorBindingStorageImageUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingStorageImageUpdateAfterBind"));
	private static final OfInt descriptorBindingStorageBufferUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingStorageBufferUpdateAfterBind"));
	private static final long descriptorBindingStorageBufferUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingStorageBufferUpdateAfterBind"));
	private static final OfInt descriptorBindingUniformTexelBufferUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingUniformTexelBufferUpdateAfterBind"));
	private static final long descriptorBindingUniformTexelBufferUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingUniformTexelBufferUpdateAfterBind"));
	private static final OfInt descriptorBindingStorageTexelBufferUpdateAfterBind$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingStorageTexelBufferUpdateAfterBind"));
	private static final long descriptorBindingStorageTexelBufferUpdateAfterBind$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingStorageTexelBufferUpdateAfterBind"));
	private static final OfInt descriptorBindingUpdateUnusedWhilePending$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingUpdateUnusedWhilePending"));
	private static final long descriptorBindingUpdateUnusedWhilePending$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingUpdateUnusedWhilePending"));
	private static final OfInt descriptorBindingPartiallyBound$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingPartiallyBound"));
	private static final long descriptorBindingPartiallyBound$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingPartiallyBound"));
	private static final OfInt descriptorBindingVariableDescriptorCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("descriptorBindingVariableDescriptorCount"));
	private static final long descriptorBindingVariableDescriptorCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("descriptorBindingVariableDescriptorCount"));
	private static final OfInt runtimeDescriptorArray$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("runtimeDescriptorArray"));
	private static final long runtimeDescriptorArray$OFFSET =
			$LAYOUT.byteOffset(groupElement("runtimeDescriptorArray"));
	private static final OfInt samplerFilterMinmax$LAYOUT = (OfInt) $LAYOUT.select(groupElement("samplerFilterMinmax"));
	private static final long samplerFilterMinmax$OFFSET = $LAYOUT.byteOffset(groupElement("samplerFilterMinmax"));
	private static final OfInt scalarBlockLayout$LAYOUT = (OfInt) $LAYOUT.select(groupElement("scalarBlockLayout"));
	private static final long scalarBlockLayout$OFFSET = $LAYOUT.byteOffset(groupElement("scalarBlockLayout"));
	private static final OfInt imagelessFramebuffer$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("imagelessFramebuffer"));
	private static final long imagelessFramebuffer$OFFSET = $LAYOUT.byteOffset(groupElement("imagelessFramebuffer"));
	private static final OfInt uniformBufferStandardLayout$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("uniformBufferStandardLayout"));
	private static final long uniformBufferStandardLayout$OFFSET =
			$LAYOUT.byteOffset(groupElement("uniformBufferStandardLayout"));
	private static final OfInt shaderSubgroupExtendedTypes$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderSubgroupExtendedTypes"));
	private static final long shaderSubgroupExtendedTypes$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderSubgroupExtendedTypes"));
	private static final OfInt separateDepthStencilLayouts$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("separateDepthStencilLayouts"));
	private static final long separateDepthStencilLayouts$OFFSET =
			$LAYOUT.byteOffset(groupElement("separateDepthStencilLayouts"));
	private static final OfInt hostQueryReset$LAYOUT = (OfInt) $LAYOUT.select(groupElement("hostQueryReset"));
	private static final long hostQueryReset$OFFSET = $LAYOUT.byteOffset(groupElement("hostQueryReset"));
	private static final OfInt timelineSemaphore$LAYOUT = (OfInt) $LAYOUT.select(groupElement("timelineSemaphore"));
	private static final long timelineSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("timelineSemaphore"));
	private static final OfInt bufferDeviceAddress$LAYOUT = (OfInt) $LAYOUT.select(groupElement("bufferDeviceAddress"));
	private static final long bufferDeviceAddress$OFFSET = $LAYOUT.byteOffset(groupElement("bufferDeviceAddress"));
	private static final OfInt bufferDeviceAddressCaptureReplay$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("bufferDeviceAddressCaptureReplay"));
	private static final long bufferDeviceAddressCaptureReplay$OFFSET =
			$LAYOUT.byteOffset(groupElement("bufferDeviceAddressCaptureReplay"));
	private static final OfInt bufferDeviceAddressMultiDevice$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("bufferDeviceAddressMultiDevice"));
	private static final long bufferDeviceAddressMultiDevice$OFFSET =
			$LAYOUT.byteOffset(groupElement("bufferDeviceAddressMultiDevice"));
	private static final OfInt vulkanMemoryModel$LAYOUT = (OfInt) $LAYOUT.select(groupElement("vulkanMemoryModel"));
	private static final long vulkanMemoryModel$OFFSET = $LAYOUT.byteOffset(groupElement("vulkanMemoryModel"));
	private static final OfInt vulkanMemoryModelDeviceScope$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("vulkanMemoryModelDeviceScope"));
	private static final long vulkanMemoryModelDeviceScope$OFFSET =
			$LAYOUT.byteOffset(groupElement("vulkanMemoryModelDeviceScope"));
	private static final OfInt vulkanMemoryModelAvailabilityVisibilityChains$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("vulkanMemoryModelAvailabilityVisibilityChains"));
	private static final long vulkanMemoryModelAvailabilityVisibilityChains$OFFSET =
			$LAYOUT.byteOffset(groupElement("vulkanMemoryModelAvailabilityVisibilityChains"));
	private static final OfInt shaderOutputViewportIndex$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderOutputViewportIndex"));
	private static final long shaderOutputViewportIndex$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderOutputViewportIndex"));
	private static final OfInt shaderOutputLayer$LAYOUT = (OfInt) $LAYOUT.select(groupElement("shaderOutputLayer"));
	private static final long shaderOutputLayer$OFFSET = $LAYOUT.byteOffset(groupElement("shaderOutputLayer"));
	private static final OfInt subgroupBroadcastDynamicId$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("subgroupBroadcastDynamicId"));
	private static final long subgroupBroadcastDynamicId$OFFSET =
			$LAYOUT.byteOffset(groupElement("subgroupBroadcastDynamicId"));

	VkPhysicalDeviceVulkan12Features()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerMirrorClampToEdge
	 *}
	 */
	public static final OfInt samplerMirrorClampToEdge$layout()
	{
		return samplerMirrorClampToEdge$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerMirrorClampToEdge
	 *}
	 */
	public static final long samplerMirrorClampToEdge$offset()
	{
		return samplerMirrorClampToEdge$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerMirrorClampToEdge
	 *}
	 */
	public static int samplerMirrorClampToEdge(MemorySegment struct)
	{
		return struct.get(samplerMirrorClampToEdge$LAYOUT, samplerMirrorClampToEdge$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerMirrorClampToEdge
	 *}
	 */
	public static void samplerMirrorClampToEdge(MemorySegment struct, int fieldValue)
	{
		struct.set(samplerMirrorClampToEdge$LAYOUT, samplerMirrorClampToEdge$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 drawIndirectCount
	 *}
	 */
	public static final OfInt drawIndirectCount$layout()
	{
		return drawIndirectCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 drawIndirectCount
	 *}
	 */
	public static final long drawIndirectCount$offset()
	{
		return drawIndirectCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 drawIndirectCount
	 *}
	 */
	public static int drawIndirectCount(MemorySegment struct)
	{
		return struct.get(drawIndirectCount$LAYOUT, drawIndirectCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 drawIndirectCount
	 *}
	 */
	public static void drawIndirectCount(MemorySegment struct, int fieldValue)
	{
		struct.set(drawIndirectCount$LAYOUT, drawIndirectCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 storageBuffer8BitAccess
	 *}
	 */
	public static final OfInt storageBuffer8BitAccess$layout()
	{
		return storageBuffer8BitAccess$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 storageBuffer8BitAccess
	 *}
	 */
	public static final long storageBuffer8BitAccess$offset()
	{
		return storageBuffer8BitAccess$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 storageBuffer8BitAccess
	 *}
	 */
	public static int storageBuffer8BitAccess(MemorySegment struct)
	{
		return struct.get(storageBuffer8BitAccess$LAYOUT, storageBuffer8BitAccess$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 storageBuffer8BitAccess
	 *}
	 */
	public static void storageBuffer8BitAccess(MemorySegment struct, int fieldValue)
	{
		struct.set(storageBuffer8BitAccess$LAYOUT, storageBuffer8BitAccess$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformAndStorageBuffer8BitAccess
	 *}
	 */
	public static final OfInt uniformAndStorageBuffer8BitAccess$layout()
	{
		return uniformAndStorageBuffer8BitAccess$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformAndStorageBuffer8BitAccess
	 *}
	 */
	public static final long uniformAndStorageBuffer8BitAccess$offset()
	{
		return uniformAndStorageBuffer8BitAccess$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformAndStorageBuffer8BitAccess
	 *}
	 */
	public static int uniformAndStorageBuffer8BitAccess(MemorySegment struct)
	{
		return struct.get(uniformAndStorageBuffer8BitAccess$LAYOUT, uniformAndStorageBuffer8BitAccess$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformAndStorageBuffer8BitAccess
	 *}
	 */
	public static void uniformAndStorageBuffer8BitAccess(MemorySegment struct, int fieldValue)
	{
		struct.set(uniformAndStorageBuffer8BitAccess$LAYOUT, uniformAndStorageBuffer8BitAccess$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 storagePushConstant8
	 *}
	 */
	public static final OfInt storagePushConstant8$layout()
	{
		return storagePushConstant8$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 storagePushConstant8
	 *}
	 */
	public static final long storagePushConstant8$offset()
	{
		return storagePushConstant8$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 storagePushConstant8
	 *}
	 */
	public static int storagePushConstant8(MemorySegment struct)
	{
		return struct.get(storagePushConstant8$LAYOUT, storagePushConstant8$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 storagePushConstant8
	 *}
	 */
	public static void storagePushConstant8(MemorySegment struct, int fieldValue)
	{
		struct.set(storagePushConstant8$LAYOUT, storagePushConstant8$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderBufferInt64Atomics
	 *}
	 */
	public static final OfInt shaderBufferInt64Atomics$layout()
	{
		return shaderBufferInt64Atomics$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderBufferInt64Atomics
	 *}
	 */
	public static final long shaderBufferInt64Atomics$offset()
	{
		return shaderBufferInt64Atomics$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderBufferInt64Atomics
	 *}
	 */
	public static int shaderBufferInt64Atomics(MemorySegment struct)
	{
		return struct.get(shaderBufferInt64Atomics$LAYOUT, shaderBufferInt64Atomics$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderBufferInt64Atomics
	 *}
	 */
	public static void shaderBufferInt64Atomics(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderBufferInt64Atomics$LAYOUT, shaderBufferInt64Atomics$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSharedInt64Atomics
	 *}
	 */
	public static final OfInt shaderSharedInt64Atomics$layout()
	{
		return shaderSharedInt64Atomics$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSharedInt64Atomics
	 *}
	 */
	public static final long shaderSharedInt64Atomics$offset()
	{
		return shaderSharedInt64Atomics$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSharedInt64Atomics
	 *}
	 */
	public static int shaderSharedInt64Atomics(MemorySegment struct)
	{
		return struct.get(shaderSharedInt64Atomics$LAYOUT, shaderSharedInt64Atomics$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSharedInt64Atomics
	 *}
	 */
	public static void shaderSharedInt64Atomics(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderSharedInt64Atomics$LAYOUT, shaderSharedInt64Atomics$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderFloat16
	 *}
	 */
	public static final OfInt shaderFloat16$layout()
	{
		return shaderFloat16$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderFloat16
	 *}
	 */
	public static final long shaderFloat16$offset()
	{
		return shaderFloat16$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderFloat16
	 *}
	 */
	public static int shaderFloat16(MemorySegment struct)
	{
		return struct.get(shaderFloat16$LAYOUT, shaderFloat16$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderFloat16
	 *}
	 */
	public static void shaderFloat16(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderFloat16$LAYOUT, shaderFloat16$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInt8
	 *}
	 */
	public static final OfInt shaderInt8$layout()
	{
		return shaderInt8$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInt8
	 *}
	 */
	public static final long shaderInt8$offset()
	{
		return shaderInt8$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInt8
	 *}
	 */
	public static int shaderInt8(MemorySegment struct)
	{
		return struct.get(shaderInt8$LAYOUT, shaderInt8$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInt8
	 *}
	 */
	public static void shaderInt8(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderInt8$LAYOUT, shaderInt8$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorIndexing
	 *}
	 */
	public static final OfInt descriptorIndexing$layout()
	{
		return descriptorIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorIndexing
	 *}
	 */
	public static final long descriptorIndexing$offset()
	{
		return descriptorIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorIndexing
	 *}
	 */
	public static int descriptorIndexing(MemorySegment struct)
	{
		return struct.get(descriptorIndexing$LAYOUT, descriptorIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorIndexing
	 *}
	 */
	public static void descriptorIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorIndexing$LAYOUT, descriptorIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayDynamicIndexing
	 *}
	 */
	public static final OfInt shaderInputAttachmentArrayDynamicIndexing$layout()
	{
		return shaderInputAttachmentArrayDynamicIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayDynamicIndexing
	 *}
	 */
	public static final long shaderInputAttachmentArrayDynamicIndexing$offset()
	{
		return shaderInputAttachmentArrayDynamicIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayDynamicIndexing
	 *}
	 */
	public static int shaderInputAttachmentArrayDynamicIndexing(MemorySegment struct)
	{
		return struct.get(shaderInputAttachmentArrayDynamicIndexing$LAYOUT,
				shaderInputAttachmentArrayDynamicIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayDynamicIndexing
	 *}
	 */
	public static void shaderInputAttachmentArrayDynamicIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderInputAttachmentArrayDynamicIndexing$LAYOUT, shaderInputAttachmentArrayDynamicIndexing$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static final OfInt shaderUniformTexelBufferArrayDynamicIndexing$layout()
	{
		return shaderUniformTexelBufferArrayDynamicIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static final long shaderUniformTexelBufferArrayDynamicIndexing$offset()
	{
		return shaderUniformTexelBufferArrayDynamicIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static int shaderUniformTexelBufferArrayDynamicIndexing(MemorySegment struct)
	{
		return struct.get(shaderUniformTexelBufferArrayDynamicIndexing$LAYOUT,
				shaderUniformTexelBufferArrayDynamicIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static void shaderUniformTexelBufferArrayDynamicIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderUniformTexelBufferArrayDynamicIndexing$LAYOUT,
				shaderUniformTexelBufferArrayDynamicIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static final OfInt shaderStorageTexelBufferArrayDynamicIndexing$layout()
	{
		return shaderStorageTexelBufferArrayDynamicIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static final long shaderStorageTexelBufferArrayDynamicIndexing$offset()
	{
		return shaderStorageTexelBufferArrayDynamicIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static int shaderStorageTexelBufferArrayDynamicIndexing(MemorySegment struct)
	{
		return struct.get(shaderStorageTexelBufferArrayDynamicIndexing$LAYOUT,
				shaderStorageTexelBufferArrayDynamicIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing
	 *}
	 */
	public static void shaderStorageTexelBufferArrayDynamicIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderStorageTexelBufferArrayDynamicIndexing$LAYOUT,
				shaderStorageTexelBufferArrayDynamicIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformBufferArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderUniformBufferArrayNonUniformIndexing$layout()
	{
		return shaderUniformBufferArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformBufferArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderUniformBufferArrayNonUniformIndexing$offset()
	{
		return shaderUniformBufferArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformBufferArrayNonUniformIndexing
	 *}
	 */
	public static int shaderUniformBufferArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderUniformBufferArrayNonUniformIndexing$LAYOUT,
				shaderUniformBufferArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformBufferArrayNonUniformIndexing
	 *}
	 */
	public static void shaderUniformBufferArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderUniformBufferArrayNonUniformIndexing$LAYOUT, shaderUniformBufferArrayNonUniformIndexing$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSampledImageArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderSampledImageArrayNonUniformIndexing$layout()
	{
		return shaderSampledImageArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSampledImageArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderSampledImageArrayNonUniformIndexing$offset()
	{
		return shaderSampledImageArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSampledImageArrayNonUniformIndexing
	 *}
	 */
	public static int shaderSampledImageArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderSampledImageArrayNonUniformIndexing$LAYOUT,
				shaderSampledImageArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSampledImageArrayNonUniformIndexing
	 *}
	 */
	public static void shaderSampledImageArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderSampledImageArrayNonUniformIndexing$LAYOUT, shaderSampledImageArrayNonUniformIndexing$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageBufferArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderStorageBufferArrayNonUniformIndexing$layout()
	{
		return shaderStorageBufferArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageBufferArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderStorageBufferArrayNonUniformIndexing$offset()
	{
		return shaderStorageBufferArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageBufferArrayNonUniformIndexing
	 *}
	 */
	public static int shaderStorageBufferArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderStorageBufferArrayNonUniformIndexing$LAYOUT,
				shaderStorageBufferArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageBufferArrayNonUniformIndexing
	 *}
	 */
	public static void shaderStorageBufferArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderStorageBufferArrayNonUniformIndexing$LAYOUT, shaderStorageBufferArrayNonUniformIndexing$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageImageArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderStorageImageArrayNonUniformIndexing$layout()
	{
		return shaderStorageImageArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageImageArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderStorageImageArrayNonUniformIndexing$offset()
	{
		return shaderStorageImageArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageImageArrayNonUniformIndexing
	 *}
	 */
	public static int shaderStorageImageArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderStorageImageArrayNonUniformIndexing$LAYOUT,
				shaderStorageImageArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageImageArrayNonUniformIndexing
	 *}
	 */
	public static void shaderStorageImageArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderStorageImageArrayNonUniformIndexing$LAYOUT, shaderStorageImageArrayNonUniformIndexing$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderInputAttachmentArrayNonUniformIndexing$layout()
	{
		return shaderInputAttachmentArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderInputAttachmentArrayNonUniformIndexing$offset()
	{
		return shaderInputAttachmentArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayNonUniformIndexing
	 *}
	 */
	public static int shaderInputAttachmentArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderInputAttachmentArrayNonUniformIndexing$LAYOUT,
				shaderInputAttachmentArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderInputAttachmentArrayNonUniformIndexing
	 *}
	 */
	public static void shaderInputAttachmentArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderInputAttachmentArrayNonUniformIndexing$LAYOUT,
				shaderInputAttachmentArrayNonUniformIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderUniformTexelBufferArrayNonUniformIndexing$layout()
	{
		return shaderUniformTexelBufferArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderUniformTexelBufferArrayNonUniformIndexing$offset()
	{
		return shaderUniformTexelBufferArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static int shaderUniformTexelBufferArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderUniformTexelBufferArrayNonUniformIndexing$LAYOUT,
				shaderUniformTexelBufferArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static void shaderUniformTexelBufferArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderUniformTexelBufferArrayNonUniformIndexing$LAYOUT,
				shaderUniformTexelBufferArrayNonUniformIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static final OfInt shaderStorageTexelBufferArrayNonUniformIndexing$layout()
	{
		return shaderStorageTexelBufferArrayNonUniformIndexing$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static final long shaderStorageTexelBufferArrayNonUniformIndexing$offset()
	{
		return shaderStorageTexelBufferArrayNonUniformIndexing$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static int shaderStorageTexelBufferArrayNonUniformIndexing(MemorySegment struct)
	{
		return struct.get(shaderStorageTexelBufferArrayNonUniformIndexing$LAYOUT,
				shaderStorageTexelBufferArrayNonUniformIndexing$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing
	 *}
	 */
	public static void shaderStorageTexelBufferArrayNonUniformIndexing(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderStorageTexelBufferArrayNonUniformIndexing$LAYOUT,
				shaderStorageTexelBufferArrayNonUniformIndexing$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformBufferUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingUniformBufferUpdateAfterBind$layout()
	{
		return descriptorBindingUniformBufferUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformBufferUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingUniformBufferUpdateAfterBind$offset()
	{
		return descriptorBindingUniformBufferUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformBufferUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingUniformBufferUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingUniformBufferUpdateAfterBind$LAYOUT,
				descriptorBindingUniformBufferUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformBufferUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingUniformBufferUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingUniformBufferUpdateAfterBind$LAYOUT,
				descriptorBindingUniformBufferUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingSampledImageUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingSampledImageUpdateAfterBind$layout()
	{
		return descriptorBindingSampledImageUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingSampledImageUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingSampledImageUpdateAfterBind$offset()
	{
		return descriptorBindingSampledImageUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingSampledImageUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingSampledImageUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingSampledImageUpdateAfterBind$LAYOUT,
				descriptorBindingSampledImageUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingSampledImageUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingSampledImageUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingSampledImageUpdateAfterBind$LAYOUT,
				descriptorBindingSampledImageUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageImageUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingStorageImageUpdateAfterBind$layout()
	{
		return descriptorBindingStorageImageUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageImageUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingStorageImageUpdateAfterBind$offset()
	{
		return descriptorBindingStorageImageUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageImageUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingStorageImageUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingStorageImageUpdateAfterBind$LAYOUT,
				descriptorBindingStorageImageUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageImageUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingStorageImageUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingStorageImageUpdateAfterBind$LAYOUT,
				descriptorBindingStorageImageUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageBufferUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingStorageBufferUpdateAfterBind$layout()
	{
		return descriptorBindingStorageBufferUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageBufferUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingStorageBufferUpdateAfterBind$offset()
	{
		return descriptorBindingStorageBufferUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageBufferUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingStorageBufferUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingStorageBufferUpdateAfterBind$LAYOUT,
				descriptorBindingStorageBufferUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageBufferUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingStorageBufferUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingStorageBufferUpdateAfterBind$LAYOUT,
				descriptorBindingStorageBufferUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingUniformTexelBufferUpdateAfterBind$layout()
	{
		return descriptorBindingUniformTexelBufferUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingUniformTexelBufferUpdateAfterBind$offset()
	{
		return descriptorBindingUniformTexelBufferUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingUniformTexelBufferUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingUniformTexelBufferUpdateAfterBind$LAYOUT,
				descriptorBindingUniformTexelBufferUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingUniformTexelBufferUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingUniformTexelBufferUpdateAfterBind$LAYOUT,
				descriptorBindingUniformTexelBufferUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind
	 *}
	 */
	public static final OfInt descriptorBindingStorageTexelBufferUpdateAfterBind$layout()
	{
		return descriptorBindingStorageTexelBufferUpdateAfterBind$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind
	 *}
	 */
	public static final long descriptorBindingStorageTexelBufferUpdateAfterBind$offset()
	{
		return descriptorBindingStorageTexelBufferUpdateAfterBind$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind
	 *}
	 */
	public static int descriptorBindingStorageTexelBufferUpdateAfterBind(MemorySegment struct)
	{
		return struct.get(descriptorBindingStorageTexelBufferUpdateAfterBind$LAYOUT,
				descriptorBindingStorageTexelBufferUpdateAfterBind$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind
	 *}
	 */
	public static void descriptorBindingStorageTexelBufferUpdateAfterBind(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingStorageTexelBufferUpdateAfterBind$LAYOUT,
				descriptorBindingStorageTexelBufferUpdateAfterBind$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUpdateUnusedWhilePending
	 *}
	 */
	public static final OfInt descriptorBindingUpdateUnusedWhilePending$layout()
	{
		return descriptorBindingUpdateUnusedWhilePending$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUpdateUnusedWhilePending
	 *}
	 */
	public static final long descriptorBindingUpdateUnusedWhilePending$offset()
	{
		return descriptorBindingUpdateUnusedWhilePending$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUpdateUnusedWhilePending
	 *}
	 */
	public static int descriptorBindingUpdateUnusedWhilePending(MemorySegment struct)
	{
		return struct.get(descriptorBindingUpdateUnusedWhilePending$LAYOUT,
				descriptorBindingUpdateUnusedWhilePending$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingUpdateUnusedWhilePending
	 *}
	 */
	public static void descriptorBindingUpdateUnusedWhilePending(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingUpdateUnusedWhilePending$LAYOUT, descriptorBindingUpdateUnusedWhilePending$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingPartiallyBound
	 *}
	 */
	public static final OfInt descriptorBindingPartiallyBound$layout()
	{
		return descriptorBindingPartiallyBound$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingPartiallyBound
	 *}
	 */
	public static final long descriptorBindingPartiallyBound$offset()
	{
		return descriptorBindingPartiallyBound$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingPartiallyBound
	 *}
	 */
	public static int descriptorBindingPartiallyBound(MemorySegment struct)
	{
		return struct.get(descriptorBindingPartiallyBound$LAYOUT, descriptorBindingPartiallyBound$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingPartiallyBound
	 *}
	 */
	public static void descriptorBindingPartiallyBound(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingPartiallyBound$LAYOUT, descriptorBindingPartiallyBound$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingVariableDescriptorCount
	 *}
	 */
	public static final OfInt descriptorBindingVariableDescriptorCount$layout()
	{
		return descriptorBindingVariableDescriptorCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingVariableDescriptorCount
	 *}
	 */
	public static final long descriptorBindingVariableDescriptorCount$offset()
	{
		return descriptorBindingVariableDescriptorCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingVariableDescriptorCount
	 *}
	 */
	public static int descriptorBindingVariableDescriptorCount(MemorySegment struct)
	{
		return struct.get(descriptorBindingVariableDescriptorCount$LAYOUT,
				descriptorBindingVariableDescriptorCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 descriptorBindingVariableDescriptorCount
	 *}
	 */
	public static void descriptorBindingVariableDescriptorCount(MemorySegment struct, int fieldValue)
	{
		struct.set(descriptorBindingVariableDescriptorCount$LAYOUT, descriptorBindingVariableDescriptorCount$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 runtimeDescriptorArray
	 *}
	 */
	public static final OfInt runtimeDescriptorArray$layout()
	{
		return runtimeDescriptorArray$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 runtimeDescriptorArray
	 *}
	 */
	public static final long runtimeDescriptorArray$offset()
	{
		return runtimeDescriptorArray$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 runtimeDescriptorArray
	 *}
	 */
	public static int runtimeDescriptorArray(MemorySegment struct)
	{
		return struct.get(runtimeDescriptorArray$LAYOUT, runtimeDescriptorArray$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 runtimeDescriptorArray
	 *}
	 */
	public static void runtimeDescriptorArray(MemorySegment struct, int fieldValue)
	{
		struct.set(runtimeDescriptorArray$LAYOUT, runtimeDescriptorArray$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerFilterMinmax
	 *}
	 */
	public static final OfInt samplerFilterMinmax$layout()
	{
		return samplerFilterMinmax$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerFilterMinmax
	 *}
	 */
	public static final long samplerFilterMinmax$offset()
	{
		return samplerFilterMinmax$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerFilterMinmax
	 *}
	 */
	public static int samplerFilterMinmax(MemorySegment struct)
	{
		return struct.get(samplerFilterMinmax$LAYOUT, samplerFilterMinmax$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 samplerFilterMinmax
	 *}
	 */
	public static void samplerFilterMinmax(MemorySegment struct, int fieldValue)
	{
		struct.set(samplerFilterMinmax$LAYOUT, samplerFilterMinmax$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 scalarBlockLayout
	 *}
	 */
	public static final OfInt scalarBlockLayout$layout()
	{
		return scalarBlockLayout$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 scalarBlockLayout
	 *}
	 */
	public static final long scalarBlockLayout$offset()
	{
		return scalarBlockLayout$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 scalarBlockLayout
	 *}
	 */
	public static int scalarBlockLayout(MemorySegment struct)
	{
		return struct.get(scalarBlockLayout$LAYOUT, scalarBlockLayout$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 scalarBlockLayout
	 *}
	 */
	public static void scalarBlockLayout(MemorySegment struct, int fieldValue)
	{
		struct.set(scalarBlockLayout$LAYOUT, scalarBlockLayout$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 imagelessFramebuffer
	 *}
	 */
	public static final OfInt imagelessFramebuffer$layout()
	{
		return imagelessFramebuffer$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 imagelessFramebuffer
	 *}
	 */
	public static final long imagelessFramebuffer$offset()
	{
		return imagelessFramebuffer$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 imagelessFramebuffer
	 *}
	 */
	public static int imagelessFramebuffer(MemorySegment struct)
	{
		return struct.get(imagelessFramebuffer$LAYOUT, imagelessFramebuffer$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 imagelessFramebuffer
	 *}
	 */
	public static void imagelessFramebuffer(MemorySegment struct, int fieldValue)
	{
		struct.set(imagelessFramebuffer$LAYOUT, imagelessFramebuffer$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformBufferStandardLayout
	 *}
	 */
	public static final OfInt uniformBufferStandardLayout$layout()
	{
		return uniformBufferStandardLayout$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformBufferStandardLayout
	 *}
	 */
	public static final long uniformBufferStandardLayout$offset()
	{
		return uniformBufferStandardLayout$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformBufferStandardLayout
	 *}
	 */
	public static int uniformBufferStandardLayout(MemorySegment struct)
	{
		return struct.get(uniformBufferStandardLayout$LAYOUT, uniformBufferStandardLayout$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 uniformBufferStandardLayout
	 *}
	 */
	public static void uniformBufferStandardLayout(MemorySegment struct, int fieldValue)
	{
		struct.set(uniformBufferStandardLayout$LAYOUT, uniformBufferStandardLayout$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSubgroupExtendedTypes
	 *}
	 */
	public static final OfInt shaderSubgroupExtendedTypes$layout()
	{
		return shaderSubgroupExtendedTypes$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSubgroupExtendedTypes
	 *}
	 */
	public static final long shaderSubgroupExtendedTypes$offset()
	{
		return shaderSubgroupExtendedTypes$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSubgroupExtendedTypes
	 *}
	 */
	public static int shaderSubgroupExtendedTypes(MemorySegment struct)
	{
		return struct.get(shaderSubgroupExtendedTypes$LAYOUT, shaderSubgroupExtendedTypes$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderSubgroupExtendedTypes
	 *}
	 */
	public static void shaderSubgroupExtendedTypes(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderSubgroupExtendedTypes$LAYOUT, shaderSubgroupExtendedTypes$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 separateDepthStencilLayouts
	 *}
	 */
	public static final OfInt separateDepthStencilLayouts$layout()
	{
		return separateDepthStencilLayouts$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 separateDepthStencilLayouts
	 *}
	 */
	public static final long separateDepthStencilLayouts$offset()
	{
		return separateDepthStencilLayouts$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 separateDepthStencilLayouts
	 *}
	 */
	public static int separateDepthStencilLayouts(MemorySegment struct)
	{
		return struct.get(separateDepthStencilLayouts$LAYOUT, separateDepthStencilLayouts$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 separateDepthStencilLayouts
	 *}
	 */
	public static void separateDepthStencilLayouts(MemorySegment struct, int fieldValue)
	{
		struct.set(separateDepthStencilLayouts$LAYOUT, separateDepthStencilLayouts$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 hostQueryReset
	 *}
	 */
	public static final OfInt hostQueryReset$layout()
	{
		return hostQueryReset$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 hostQueryReset
	 *}
	 */
	public static final long hostQueryReset$offset()
	{
		return hostQueryReset$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 hostQueryReset
	 *}
	 */
	public static int hostQueryReset(MemorySegment struct)
	{
		return struct.get(hostQueryReset$LAYOUT, hostQueryReset$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 hostQueryReset
	 *}
	 */
	public static void hostQueryReset(MemorySegment struct, int fieldValue)
	{
		struct.set(hostQueryReset$LAYOUT, hostQueryReset$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 timelineSemaphore
	 *}
	 */
	public static final OfInt timelineSemaphore$layout()
	{
		return timelineSemaphore$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 timelineSemaphore
	 *}
	 */
	public static final long timelineSemaphore$offset()
	{
		return timelineSemaphore$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 timelineSemaphore
	 *}
	 */
	public static int timelineSemaphore(MemorySegment struct)
	{
		return struct.get(timelineSemaphore$LAYOUT, timelineSemaphore$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 timelineSemaphore
	 *}
	 */
	public static void timelineSemaphore(MemorySegment struct, int fieldValue)
	{
		struct.set(timelineSemaphore$LAYOUT, timelineSemaphore$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddress
	 *}
	 */
	public static final OfInt bufferDeviceAddress$layout()
	{
		return bufferDeviceAddress$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddress
	 *}
	 */
	public static final long bufferDeviceAddress$offset()
	{
		return bufferDeviceAddress$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddress
	 *}
	 */
	public static int bufferDeviceAddress(MemorySegment struct)
	{
		return struct.get(bufferDeviceAddress$LAYOUT, bufferDeviceAddress$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddress
	 *}
	 */
	public static void bufferDeviceAddress(MemorySegment struct, int fieldValue)
	{
		struct.set(bufferDeviceAddress$LAYOUT, bufferDeviceAddress$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressCaptureReplay
	 *}
	 */
	public static final OfInt bufferDeviceAddressCaptureReplay$layout()
	{
		return bufferDeviceAddressCaptureReplay$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressCaptureReplay
	 *}
	 */
	public static final long bufferDeviceAddressCaptureReplay$offset()
	{
		return bufferDeviceAddressCaptureReplay$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressCaptureReplay
	 *}
	 */
	public static int bufferDeviceAddressCaptureReplay(MemorySegment struct)
	{
		return struct.get(bufferDeviceAddressCaptureReplay$LAYOUT, bufferDeviceAddressCaptureReplay$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressCaptureReplay
	 *}
	 */
	public static void bufferDeviceAddressCaptureReplay(MemorySegment struct, int fieldValue)
	{
		struct.set(bufferDeviceAddressCaptureReplay$LAYOUT, bufferDeviceAddressCaptureReplay$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressMultiDevice
	 *}
	 */
	public static final OfInt bufferDeviceAddressMultiDevice$layout()
	{
		return bufferDeviceAddressMultiDevice$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressMultiDevice
	 *}
	 */
	public static final long bufferDeviceAddressMultiDevice$offset()
	{
		return bufferDeviceAddressMultiDevice$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressMultiDevice
	 *}
	 */
	public static int bufferDeviceAddressMultiDevice(MemorySegment struct)
	{
		return struct.get(bufferDeviceAddressMultiDevice$LAYOUT, bufferDeviceAddressMultiDevice$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 bufferDeviceAddressMultiDevice
	 *}
	 */
	public static void bufferDeviceAddressMultiDevice(MemorySegment struct, int fieldValue)
	{
		struct.set(bufferDeviceAddressMultiDevice$LAYOUT, bufferDeviceAddressMultiDevice$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModel
	 *}
	 */
	public static final OfInt vulkanMemoryModel$layout()
	{
		return vulkanMemoryModel$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModel
	 *}
	 */
	public static final long vulkanMemoryModel$offset()
	{
		return vulkanMemoryModel$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModel
	 *}
	 */
	public static int vulkanMemoryModel(MemorySegment struct)
	{
		return struct.get(vulkanMemoryModel$LAYOUT, vulkanMemoryModel$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModel
	 *}
	 */
	public static void vulkanMemoryModel(MemorySegment struct, int fieldValue)
	{
		struct.set(vulkanMemoryModel$LAYOUT, vulkanMemoryModel$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelDeviceScope
	 *}
	 */
	public static final OfInt vulkanMemoryModelDeviceScope$layout()
	{
		return vulkanMemoryModelDeviceScope$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelDeviceScope
	 *}
	 */
	public static final long vulkanMemoryModelDeviceScope$offset()
	{
		return vulkanMemoryModelDeviceScope$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelDeviceScope
	 *}
	 */
	public static int vulkanMemoryModelDeviceScope(MemorySegment struct)
	{
		return struct.get(vulkanMemoryModelDeviceScope$LAYOUT, vulkanMemoryModelDeviceScope$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelDeviceScope
	 *}
	 */
	public static void vulkanMemoryModelDeviceScope(MemorySegment struct, int fieldValue)
	{
		struct.set(vulkanMemoryModelDeviceScope$LAYOUT, vulkanMemoryModelDeviceScope$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelAvailabilityVisibilityChains
	 *}
	 */
	public static final OfInt vulkanMemoryModelAvailabilityVisibilityChains$layout()
	{
		return vulkanMemoryModelAvailabilityVisibilityChains$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelAvailabilityVisibilityChains
	 *}
	 */
	public static final long vulkanMemoryModelAvailabilityVisibilityChains$offset()
	{
		return vulkanMemoryModelAvailabilityVisibilityChains$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelAvailabilityVisibilityChains
	 *}
	 */
	public static int vulkanMemoryModelAvailabilityVisibilityChains(MemorySegment struct)
	{
		return struct.get(vulkanMemoryModelAvailabilityVisibilityChains$LAYOUT,
				vulkanMemoryModelAvailabilityVisibilityChains$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 vulkanMemoryModelAvailabilityVisibilityChains
	 *}
	 */
	public static void vulkanMemoryModelAvailabilityVisibilityChains(MemorySegment struct, int fieldValue)
	{
		struct.set(vulkanMemoryModelAvailabilityVisibilityChains$LAYOUT,
				vulkanMemoryModelAvailabilityVisibilityChains$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputViewportIndex
	 *}
	 */
	public static final OfInt shaderOutputViewportIndex$layout()
	{
		return shaderOutputViewportIndex$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputViewportIndex
	 *}
	 */
	public static final long shaderOutputViewportIndex$offset()
	{
		return shaderOutputViewportIndex$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputViewportIndex
	 *}
	 */
	public static int shaderOutputViewportIndex(MemorySegment struct)
	{
		return struct.get(shaderOutputViewportIndex$LAYOUT, shaderOutputViewportIndex$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputViewportIndex
	 *}
	 */
	public static void shaderOutputViewportIndex(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderOutputViewportIndex$LAYOUT, shaderOutputViewportIndex$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputLayer
	 *}
	 */
	public static final OfInt shaderOutputLayer$layout()
	{
		return shaderOutputLayer$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputLayer
	 *}
	 */
	public static final long shaderOutputLayer$offset()
	{
		return shaderOutputLayer$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputLayer
	 *}
	 */
	public static int shaderOutputLayer(MemorySegment struct)
	{
		return struct.get(shaderOutputLayer$LAYOUT, shaderOutputLayer$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderOutputLayer
	 *}
	 */
	public static void shaderOutputLayer(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderOutputLayer$LAYOUT, shaderOutputLayer$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 subgroupBroadcastDynamicId
	 *}
	 */
	public static final OfInt subgroupBroadcastDynamicId$layout()
	{
		return subgroupBroadcastDynamicId$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 subgroupBroadcastDynamicId
	 *}
	 */
	public static final long subgroupBroadcastDynamicId$offset()
	{
		return subgroupBroadcastDynamicId$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 subgroupBroadcastDynamicId
	 *}
	 */
	public static int subgroupBroadcastDynamicId(MemorySegment struct)
	{
		return struct.get(subgroupBroadcastDynamicId$LAYOUT, subgroupBroadcastDynamicId$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 subgroupBroadcastDynamicId
	 *}
	 */
	public static void subgroupBroadcastDynamicId(MemorySegment struct, int fieldValue)
	{
		struct.set(subgroupBroadcastDynamicId$LAYOUT, subgroupBroadcastDynamicId$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

