// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDevice8BitStorageFeatures VkPhysicalDevice8BitStorageFeaturesKHR
 *}
 */
public class VkPhysicalDevice8BitStorageFeaturesKHR extends VkPhysicalDevice8BitStorageFeatures
{

	VkPhysicalDevice8BitStorageFeaturesKHR()
	{
		// Should not be called directly
	}
}

