// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDevice16BitStorageFeatures VkPhysicalDevice16BitStorageFeaturesKHR
 *}
 */
public class VkPhysicalDevice16BitStorageFeaturesKHR extends VkPhysicalDevice16BitStorageFeatures
{

	VkPhysicalDevice16BitStorageFeaturesKHR()
	{
		// Should not be called directly
	}
}

