// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDeviceMemoryDecompressionPropertiesEXT {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkMemoryDecompressionMethodFlagsEXT decompressionMethods;
 *     uint64_t maxDecompressionIndirectCount;
 * }
 *}
 */
public class VkPhysicalDeviceMemoryDecompressionPropertiesEXT
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_LONG_LONG.withName("decompressionMethods"),
			Vulkan.C_LONG_LONG.withName("maxDecompressionIndirectCount")
	).withName("VkPhysicalDeviceMemoryDecompressionPropertiesEXT");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfLong decompressionMethods$LAYOUT =
			(OfLong) $LAYOUT.select(groupElement("decompressionMethods"));
	private static final long decompressionMethods$OFFSET = $LAYOUT.byteOffset(groupElement("decompressionMethods"));
	private static final OfLong maxDecompressionIndirectCount$LAYOUT =
			(OfLong) $LAYOUT.select(groupElement("maxDecompressionIndirectCount"));
	private static final long maxDecompressionIndirectCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxDecompressionIndirectCount"));

	VkPhysicalDeviceMemoryDecompressionPropertiesEXT()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkMemoryDecompressionMethodFlagsEXT decompressionMethods
	 *}
	 */
	public static final OfLong decompressionMethods$layout()
	{
		return decompressionMethods$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkMemoryDecompressionMethodFlagsEXT decompressionMethods
	 *}
	 */
	public static final long decompressionMethods$offset()
	{
		return decompressionMethods$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkMemoryDecompressionMethodFlagsEXT decompressionMethods
	 *}
	 */
	public static long decompressionMethods(MemorySegment struct)
	{
		return struct.get(decompressionMethods$LAYOUT, decompressionMethods$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkMemoryDecompressionMethodFlagsEXT decompressionMethods
	 *}
	 */
	public static void decompressionMethods(MemorySegment struct, long fieldValue)
	{
		struct.set(decompressionMethods$LAYOUT, decompressionMethods$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxDecompressionIndirectCount
	 *}
	 */
	public static final OfLong maxDecompressionIndirectCount$layout()
	{
		return maxDecompressionIndirectCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxDecompressionIndirectCount
	 *}
	 */
	public static final long maxDecompressionIndirectCount$offset()
	{
		return maxDecompressionIndirectCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxDecompressionIndirectCount
	 *}
	 */
	public static long maxDecompressionIndirectCount(MemorySegment struct)
	{
		return struct.get(maxDecompressionIndirectCount$LAYOUT, maxDecompressionIndirectCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxDecompressionIndirectCount
	 *}
	 */
	public static void maxDecompressionIndirectCount(MemorySegment struct, long fieldValue)
	{
		struct.set(maxDecompressionIndirectCount$LAYOUT, maxDecompressionIndirectCount$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

