// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDeviceRayTracingPropertiesNV {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t shaderGroupHandleSize;
 *     uint32_t maxRecursionDepth;
 *     uint32_t maxShaderGroupStride;
 *     uint32_t shaderGroupBaseAlignment;
 *     uint64_t maxGeometryCount;
 *     uint64_t maxInstanceCount;
 *     uint64_t maxTriangleCount;
 *     uint32_t maxDescriptorSetAccelerationStructures;
 * }
 *}
 */
public class VkPhysicalDeviceRayTracingPropertiesNV
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("shaderGroupHandleSize"),
			Vulkan.C_INT.withName("maxRecursionDepth"),
			Vulkan.C_INT.withName("maxShaderGroupStride"),
			Vulkan.C_INT.withName("shaderGroupBaseAlignment"),
			Vulkan.C_LONG_LONG.withName("maxGeometryCount"),
			Vulkan.C_LONG_LONG.withName("maxInstanceCount"),
			Vulkan.C_LONG_LONG.withName("maxTriangleCount"),
			Vulkan.C_INT.withName("maxDescriptorSetAccelerationStructures"),
			MemoryLayout.paddingLayout(4)
	).withName("VkPhysicalDeviceRayTracingPropertiesNV");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt shaderGroupHandleSize$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderGroupHandleSize"));
	private static final long shaderGroupHandleSize$OFFSET = $LAYOUT.byteOffset(groupElement("shaderGroupHandleSize"));
	private static final OfInt maxRecursionDepth$LAYOUT = (OfInt) $LAYOUT.select(groupElement("maxRecursionDepth"));
	private static final long maxRecursionDepth$OFFSET = $LAYOUT.byteOffset(groupElement("maxRecursionDepth"));
	private static final OfInt maxShaderGroupStride$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxShaderGroupStride"));
	private static final long maxShaderGroupStride$OFFSET = $LAYOUT.byteOffset(groupElement("maxShaderGroupStride"));
	private static final OfInt shaderGroupBaseAlignment$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderGroupBaseAlignment"));
	private static final long shaderGroupBaseAlignment$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderGroupBaseAlignment"));
	private static final OfLong maxGeometryCount$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxGeometryCount"));
	private static final long maxGeometryCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxGeometryCount"));
	private static final OfLong maxInstanceCount$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxInstanceCount"));
	private static final long maxInstanceCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxInstanceCount"));
	private static final OfLong maxTriangleCount$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxTriangleCount"));
	private static final long maxTriangleCount$OFFSET = $LAYOUT.byteOffset(groupElement("maxTriangleCount"));
	private static final OfInt maxDescriptorSetAccelerationStructures$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxDescriptorSetAccelerationStructures"));
	private static final long maxDescriptorSetAccelerationStructures$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxDescriptorSetAccelerationStructures"));

	VkPhysicalDeviceRayTracingPropertiesNV()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupHandleSize
	 *}
	 */
	public static final OfInt shaderGroupHandleSize$layout()
	{
		return shaderGroupHandleSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupHandleSize
	 *}
	 */
	public static final long shaderGroupHandleSize$offset()
	{
		return shaderGroupHandleSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupHandleSize
	 *}
	 */
	public static int shaderGroupHandleSize(MemorySegment struct)
	{
		return struct.get(shaderGroupHandleSize$LAYOUT, shaderGroupHandleSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupHandleSize
	 *}
	 */
	public static void shaderGroupHandleSize(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderGroupHandleSize$LAYOUT, shaderGroupHandleSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxRecursionDepth
	 *}
	 */
	public static final OfInt maxRecursionDepth$layout()
	{
		return maxRecursionDepth$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxRecursionDepth
	 *}
	 */
	public static final long maxRecursionDepth$offset()
	{
		return maxRecursionDepth$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxRecursionDepth
	 *}
	 */
	public static int maxRecursionDepth(MemorySegment struct)
	{
		return struct.get(maxRecursionDepth$LAYOUT, maxRecursionDepth$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxRecursionDepth
	 *}
	 */
	public static void maxRecursionDepth(MemorySegment struct, int fieldValue)
	{
		struct.set(maxRecursionDepth$LAYOUT, maxRecursionDepth$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxShaderGroupStride
	 *}
	 */
	public static final OfInt maxShaderGroupStride$layout()
	{
		return maxShaderGroupStride$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxShaderGroupStride
	 *}
	 */
	public static final long maxShaderGroupStride$offset()
	{
		return maxShaderGroupStride$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxShaderGroupStride
	 *}
	 */
	public static int maxShaderGroupStride(MemorySegment struct)
	{
		return struct.get(maxShaderGroupStride$LAYOUT, maxShaderGroupStride$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxShaderGroupStride
	 *}
	 */
	public static void maxShaderGroupStride(MemorySegment struct, int fieldValue)
	{
		struct.set(maxShaderGroupStride$LAYOUT, maxShaderGroupStride$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupBaseAlignment
	 *}
	 */
	public static final OfInt shaderGroupBaseAlignment$layout()
	{
		return shaderGroupBaseAlignment$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupBaseAlignment
	 *}
	 */
	public static final long shaderGroupBaseAlignment$offset()
	{
		return shaderGroupBaseAlignment$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupBaseAlignment
	 *}
	 */
	public static int shaderGroupBaseAlignment(MemorySegment struct)
	{
		return struct.get(shaderGroupBaseAlignment$LAYOUT, shaderGroupBaseAlignment$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t shaderGroupBaseAlignment
	 *}
	 */
	public static void shaderGroupBaseAlignment(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderGroupBaseAlignment$LAYOUT, shaderGroupBaseAlignment$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxGeometryCount
	 *}
	 */
	public static final OfLong maxGeometryCount$layout()
	{
		return maxGeometryCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxGeometryCount
	 *}
	 */
	public static final long maxGeometryCount$offset()
	{
		return maxGeometryCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxGeometryCount
	 *}
	 */
	public static long maxGeometryCount(MemorySegment struct)
	{
		return struct.get(maxGeometryCount$LAYOUT, maxGeometryCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxGeometryCount
	 *}
	 */
	public static void maxGeometryCount(MemorySegment struct, long fieldValue)
	{
		struct.set(maxGeometryCount$LAYOUT, maxGeometryCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxInstanceCount
	 *}
	 */
	public static final OfLong maxInstanceCount$layout()
	{
		return maxInstanceCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxInstanceCount
	 *}
	 */
	public static final long maxInstanceCount$offset()
	{
		return maxInstanceCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxInstanceCount
	 *}
	 */
	public static long maxInstanceCount(MemorySegment struct)
	{
		return struct.get(maxInstanceCount$LAYOUT, maxInstanceCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxInstanceCount
	 *}
	 */
	public static void maxInstanceCount(MemorySegment struct, long fieldValue)
	{
		struct.set(maxInstanceCount$LAYOUT, maxInstanceCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxTriangleCount
	 *}
	 */
	public static final OfLong maxTriangleCount$layout()
	{
		return maxTriangleCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxTriangleCount
	 *}
	 */
	public static final long maxTriangleCount$offset()
	{
		return maxTriangleCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTriangleCount
	 *}
	 */
	public static long maxTriangleCount(MemorySegment struct)
	{
		return struct.get(maxTriangleCount$LAYOUT, maxTriangleCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTriangleCount
	 *}
	 */
	public static void maxTriangleCount(MemorySegment struct, long fieldValue)
	{
		struct.set(maxTriangleCount$LAYOUT, maxTriangleCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetAccelerationStructures
	 *}
	 */
	public static final OfInt maxDescriptorSetAccelerationStructures$layout()
	{
		return maxDescriptorSetAccelerationStructures$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetAccelerationStructures
	 *}
	 */
	public static final long maxDescriptorSetAccelerationStructures$offset()
	{
		return maxDescriptorSetAccelerationStructures$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetAccelerationStructures
	 *}
	 */
	public static int maxDescriptorSetAccelerationStructures(MemorySegment struct)
	{
		return struct.get(maxDescriptorSetAccelerationStructures$LAYOUT, maxDescriptorSetAccelerationStructures$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetAccelerationStructures
	 *}
	 */
	public static void maxDescriptorSetAccelerationStructures(MemorySegment struct, int fieldValue)
	{
		struct.set(maxDescriptorSetAccelerationStructures$LAYOUT, maxDescriptorSetAccelerationStructures$OFFSET,
				fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

