// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPhysicalDeviceVariablePointersFeatures VkPhysicalDeviceVariablePointerFeatures
 *}
 */
public class VkPhysicalDeviceVariablePointerFeatures extends VkPhysicalDeviceVariablePointersFeatures
{

	VkPhysicalDeviceVariablePointerFeatures()
	{
		// Should not be called directly
	}
}

