// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDeviceDataGraphProcessingEngineARM {
 *     VkPhysicalDeviceDataGraphProcessingEngineTypeARM type;
 *     VkBool32 isForeign;
 * }
 *}
 */
public class VkPhysicalDeviceDataGraphProcessingEngineARM
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("type"),
			Vulkan.C_INT.withName("isForeign")
	).withName("VkPhysicalDeviceDataGraphProcessingEngineARM");
	private static final OfInt type$LAYOUT = (OfInt) $LAYOUT.select(groupElement("type"));
	private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));
	private static final OfInt isForeign$LAYOUT = (OfInt) $LAYOUT.select(groupElement("isForeign"));
	private static final long isForeign$OFFSET = $LAYOUT.byteOffset(groupElement("isForeign"));

	VkPhysicalDeviceDataGraphProcessingEngineARM()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkPhysicalDeviceDataGraphProcessingEngineTypeARM type
	 *}
	 */
	public static final OfInt type$layout()
	{
		return type$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkPhysicalDeviceDataGraphProcessingEngineTypeARM type
	 *}
	 */
	public static final long type$offset()
	{
		return type$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkPhysicalDeviceDataGraphProcessingEngineTypeARM type
	 *}
	 */
	public static int type(MemorySegment struct)
	{
		return struct.get(type$LAYOUT, type$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkPhysicalDeviceDataGraphProcessingEngineTypeARM type
	 *}
	 */
	public static void type(MemorySegment struct, int fieldValue)
	{
		struct.set(type$LAYOUT, type$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 isForeign
	 *}
	 */
	public static final OfInt isForeign$layout()
	{
		return isForeign$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 isForeign
	 *}
	 */
	public static final long isForeign$offset()
	{
		return isForeign$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 isForeign
	 *}
	 */
	public static int isForeign(MemorySegment struct)
	{
		return struct.get(isForeign$LAYOUT, isForeign$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 isForeign
	 *}
	 */
	public static void isForeign(MemorySegment struct, int fieldValue)
	{
		struct.set(isForeign$LAYOUT, isForeign$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

