// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.MemoryLayout.PathElement.sequenceElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang = c:
 * struct VkPipelineExecutableInternalRepresentationKHR {
 *     VkStructureType sType;
 *     void *pNext;
 *     char name[256];
 *     char description[256];
 *     VkBool32 isText;
 *     size_t dataSize;
 *     void *pData;
 * }
 *}
 */
public class VkPipelineExecutableInternalRepresentationKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			MemoryLayout.sequenceLayout(256, Vulkan.C_CHAR).withName("name"),
			MemoryLayout.sequenceLayout(256, Vulkan.C_CHAR).withName("description"),
			Vulkan.C_INT.withName("isText"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_LONG_LONG.withName("dataSize"),
			Vulkan.C_POINTER.withName("pData")
	).withName("VkPipelineExecutableInternalRepresentationKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final SequenceLayout name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("name"));
	private static final VarHandle name$ELEM_HANDLE = name$LAYOUT.varHandle(sequenceElement());
	private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));
	private static final SequenceLayout description$LAYOUT =
			(SequenceLayout) $LAYOUT.select(groupElement("description"));
	private static final VarHandle description$ELEM_HANDLE = description$LAYOUT.varHandle(sequenceElement());
	private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));
	private static final OfInt isText$LAYOUT = (OfInt) $LAYOUT.select(groupElement("isText"));
	private static final long isText$OFFSET = $LAYOUT.byteOffset(groupElement("isText"));
	private static final OfLong dataSize$LAYOUT = (OfLong) $LAYOUT.select(groupElement("dataSize"));
	private static final long dataSize$OFFSET = $LAYOUT.byteOffset(groupElement("dataSize"));
	private static final AddressLayout pData$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pData"));
	private static final long pData$OFFSET = $LAYOUT.byteOffset(groupElement("pData"));
	private static long[] name$DIMS = {256};
	private static long[] description$DIMS = {256};

	VkPipelineExecutableInternalRepresentationKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static final SequenceLayout name$layout()
	{
		return name$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static final long name$offset()
	{
		return name$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static MemorySegment name(MemorySegment struct)
	{
		return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static void name(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
	}

	/**
	 * Dimensions for array field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static long[] name$dimensions()
	{
		return name$DIMS;
	}

	/**
	 * Indexed getter for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static byte name(MemorySegment struct, long index0)
	{
		return (byte) name$ELEM_HANDLE.get(struct, name$OFFSET, index0);
	}

	/**
	 * Indexed setter for field:
	 * {@snippet lang = c:
	 * char name[256]
	 *}
	 */
	public static void name(MemorySegment struct, long index0, byte fieldValue)
	{
		name$ELEM_HANDLE.set(struct, name$OFFSET, index0, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static final SequenceLayout description$layout()
	{
		return description$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static final long description$offset()
	{
		return description$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static MemorySegment description(MemorySegment struct)
	{
		return struct.asSlice(description$OFFSET, description$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static void description(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, description$OFFSET, description$LAYOUT.byteSize());
	}

	/**
	 * Dimensions for array field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static long[] description$dimensions()
	{
		return description$DIMS;
	}

	/**
	 * Indexed getter for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static byte description(MemorySegment struct, long index0)
	{
		return (byte) description$ELEM_HANDLE.get(struct, description$OFFSET, index0);
	}

	/**
	 * Indexed setter for field:
	 * {@snippet lang = c:
	 * char description[256]
	 *}
	 */
	public static void description(MemorySegment struct, long index0, byte fieldValue)
	{
		description$ELEM_HANDLE.set(struct, description$OFFSET, index0, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 isText
	 *}
	 */
	public static final OfInt isText$layout()
	{
		return isText$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 isText
	 *}
	 */
	public static final long isText$offset()
	{
		return isText$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 isText
	 *}
	 */
	public static int isText(MemorySegment struct)
	{
		return struct.get(isText$LAYOUT, isText$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 isText
	 *}
	 */
	public static void isText(MemorySegment struct, int fieldValue)
	{
		struct.set(isText$LAYOUT, isText$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * size_t dataSize
	 *}
	 */
	public static final OfLong dataSize$layout()
	{
		return dataSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * size_t dataSize
	 *}
	 */
	public static final long dataSize$offset()
	{
		return dataSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * size_t dataSize
	 *}
	 */
	public static long dataSize(MemorySegment struct)
	{
		return struct.get(dataSize$LAYOUT, dataSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * size_t dataSize
	 *}
	 */
	public static void dataSize(MemorySegment struct, long fieldValue)
	{
		struct.set(dataSize$LAYOUT, dataSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pData
	 *}
	 */
	public static final AddressLayout pData$layout()
	{
		return pData$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pData
	 *}
	 */
	public static final long pData$offset()
	{
		return pData$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pData
	 *}
	 */
	public static MemorySegment pData(MemorySegment struct)
	{
		return struct.get(pData$LAYOUT, pData$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pData
	 *}
	 */
	public static void pData(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pData$LAYOUT, pData$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

