// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkPrivateDataSlotCreateInfo VkPrivateDataSlotCreateInfoEXT
 *}
 */
public class VkPrivateDataSlotCreateInfoEXT extends VkPrivateDataSlotCreateInfo
{

	VkPrivateDataSlotCreateInfoEXT()
	{
		// Should not be called directly
	}
}

