// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkRenderingInfo {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkRenderingFlags flags;
 *     VkRect2D renderArea;
 *     uint32_t layerCount;
 *     uint32_t viewMask;
 *     uint32_t colorAttachmentCount;
 *     const VkRenderingAttachmentInfo *pColorAttachments;
 *     const VkRenderingAttachmentInfo *pDepthAttachment;
 *     const VkRenderingAttachmentInfo *pStencilAttachment;
 * }
 *}
 */
public class VkRenderingInfo
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("flags"),
			VkRect2D.layout().withName("renderArea"),
			Vulkan.C_INT.withName("layerCount"),
			Vulkan.C_INT.withName("viewMask"),
			Vulkan.C_INT.withName("colorAttachmentCount"),
			Vulkan.C_POINTER.withName("pColorAttachments"),
			Vulkan.C_POINTER.withName("pDepthAttachment"),
			Vulkan.C_POINTER.withName("pStencilAttachment")
	).withName("VkRenderingInfo");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt flags$LAYOUT = (OfInt) $LAYOUT.select(groupElement("flags"));
	private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));
	private static final GroupLayout renderArea$LAYOUT = (GroupLayout) $LAYOUT.select(groupElement("renderArea"));
	private static final long renderArea$OFFSET = $LAYOUT.byteOffset(groupElement("renderArea"));
	private static final OfInt layerCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("layerCount"));
	private static final long layerCount$OFFSET = $LAYOUT.byteOffset(groupElement("layerCount"));
	private static final OfInt viewMask$LAYOUT = (OfInt) $LAYOUT.select(groupElement("viewMask"));
	private static final long viewMask$OFFSET = $LAYOUT.byteOffset(groupElement("viewMask"));
	private static final OfInt colorAttachmentCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("colorAttachmentCount"));
	private static final long colorAttachmentCount$OFFSET = $LAYOUT.byteOffset(groupElement("colorAttachmentCount"));
	private static final AddressLayout pColorAttachments$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pColorAttachments"));
	private static final long pColorAttachments$OFFSET = $LAYOUT.byteOffset(groupElement("pColorAttachments"));
	private static final AddressLayout pDepthAttachment$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pDepthAttachment"));
	private static final long pDepthAttachment$OFFSET = $LAYOUT.byteOffset(groupElement("pDepthAttachment"));
	private static final AddressLayout pStencilAttachment$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pStencilAttachment"));
	private static final long pStencilAttachment$OFFSET = $LAYOUT.byteOffset(groupElement("pStencilAttachment"));

	VkRenderingInfo()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkRenderingFlags flags
	 *}
	 */
	public static final OfInt flags$layout()
	{
		return flags$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkRenderingFlags flags
	 *}
	 */
	public static final long flags$offset()
	{
		return flags$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkRenderingFlags flags
	 *}
	 */
	public static int flags(MemorySegment struct)
	{
		return struct.get(flags$LAYOUT, flags$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkRenderingFlags flags
	 *}
	 */
	public static void flags(MemorySegment struct, int fieldValue)
	{
		struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkRect2D renderArea
	 *}
	 */
	public static final GroupLayout renderArea$layout()
	{
		return renderArea$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkRect2D renderArea
	 *}
	 */
	public static final long renderArea$offset()
	{
		return renderArea$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkRect2D renderArea
	 *}
	 */
	public static MemorySegment renderArea(MemorySegment struct)
	{
		return struct.asSlice(renderArea$OFFSET, renderArea$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkRect2D renderArea
	 *}
	 */
	public static void renderArea(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, renderArea$OFFSET, renderArea$LAYOUT.byteSize());
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t layerCount
	 *}
	 */
	public static final OfInt layerCount$layout()
	{
		return layerCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t layerCount
	 *}
	 */
	public static final long layerCount$offset()
	{
		return layerCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t layerCount
	 *}
	 */
	public static int layerCount(MemorySegment struct)
	{
		return struct.get(layerCount$LAYOUT, layerCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t layerCount
	 *}
	 */
	public static void layerCount(MemorySegment struct, int fieldValue)
	{
		struct.set(layerCount$LAYOUT, layerCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t viewMask
	 *}
	 */
	public static final OfInt viewMask$layout()
	{
		return viewMask$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t viewMask
	 *}
	 */
	public static final long viewMask$offset()
	{
		return viewMask$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t viewMask
	 *}
	 */
	public static int viewMask(MemorySegment struct)
	{
		return struct.get(viewMask$LAYOUT, viewMask$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t viewMask
	 *}
	 */
	public static void viewMask(MemorySegment struct, int fieldValue)
	{
		struct.set(viewMask$LAYOUT, viewMask$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t colorAttachmentCount
	 *}
	 */
	public static final OfInt colorAttachmentCount$layout()
	{
		return colorAttachmentCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t colorAttachmentCount
	 *}
	 */
	public static final long colorAttachmentCount$offset()
	{
		return colorAttachmentCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t colorAttachmentCount
	 *}
	 */
	public static int colorAttachmentCount(MemorySegment struct)
	{
		return struct.get(colorAttachmentCount$LAYOUT, colorAttachmentCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t colorAttachmentCount
	 *}
	 */
	public static void colorAttachmentCount(MemorySegment struct, int fieldValue)
	{
		struct.set(colorAttachmentCount$LAYOUT, colorAttachmentCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pColorAttachments
	 *}
	 */
	public static final AddressLayout pColorAttachments$layout()
	{
		return pColorAttachments$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pColorAttachments
	 *}
	 */
	public static final long pColorAttachments$offset()
	{
		return pColorAttachments$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pColorAttachments
	 *}
	 */
	public static MemorySegment pColorAttachments(MemorySegment struct)
	{
		return struct.get(pColorAttachments$LAYOUT, pColorAttachments$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pColorAttachments
	 *}
	 */
	public static void pColorAttachments(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pColorAttachments$LAYOUT, pColorAttachments$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pDepthAttachment
	 *}
	 */
	public static final AddressLayout pDepthAttachment$layout()
	{
		return pDepthAttachment$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pDepthAttachment
	 *}
	 */
	public static final long pDepthAttachment$offset()
	{
		return pDepthAttachment$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pDepthAttachment
	 *}
	 */
	public static MemorySegment pDepthAttachment(MemorySegment struct)
	{
		return struct.get(pDepthAttachment$LAYOUT, pDepthAttachment$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pDepthAttachment
	 *}
	 */
	public static void pDepthAttachment(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pDepthAttachment$LAYOUT, pDepthAttachment$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pStencilAttachment
	 *}
	 */
	public static final AddressLayout pStencilAttachment$layout()
	{
		return pStencilAttachment$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pStencilAttachment
	 *}
	 */
	public static final long pStencilAttachment$offset()
	{
		return pStencilAttachment$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pStencilAttachment
	 *}
	 */
	public static MemorySegment pStencilAttachment(MemorySegment struct)
	{
		return struct.get(pStencilAttachment$LAYOUT, pStencilAttachment$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkRenderingAttachmentInfo *pStencilAttachment
	 *}
	 */
	public static void pStencilAttachment(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pStencilAttachment$LAYOUT, pStencilAttachment$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

