// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkSubpassDescriptionDepthStencilResolve VkSubpassDescriptionDepthStencilResolveKHR
 *}
 */
public class VkSubpassDescriptionDepthStencilResolveKHR extends VkSubpassDescriptionDepthStencilResolve
{

	VkSubpassDescriptionDepthStencilResolveKHR()
	{
		// Should not be called directly
	}
}

