// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkVideoEncodeAV1GopRemainingFrameInfoKHR {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkBool32 useGopRemainingFrames;
 *     uint32_t gopRemainingIntra;
 *     uint32_t gopRemainingPredictive;
 *     uint32_t gopRemainingBipredictive;
 * }
 *}
 */
public class VkVideoEncodeAV1GopRemainingFrameInfoKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("useGopRemainingFrames"),
			Vulkan.C_INT.withName("gopRemainingIntra"),
			Vulkan.C_INT.withName("gopRemainingPredictive"),
			Vulkan.C_INT.withName("gopRemainingBipredictive")
	).withName("VkVideoEncodeAV1GopRemainingFrameInfoKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt useGopRemainingFrames$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("useGopRemainingFrames"));
	private static final long useGopRemainingFrames$OFFSET = $LAYOUT.byteOffset(groupElement("useGopRemainingFrames"));
	private static final OfInt gopRemainingIntra$LAYOUT = (OfInt) $LAYOUT.select(groupElement("gopRemainingIntra"));
	private static final long gopRemainingIntra$OFFSET = $LAYOUT.byteOffset(groupElement("gopRemainingIntra"));
	private static final OfInt gopRemainingPredictive$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("gopRemainingPredictive"));
	private static final long gopRemainingPredictive$OFFSET =
			$LAYOUT.byteOffset(groupElement("gopRemainingPredictive"));
	private static final OfInt gopRemainingBipredictive$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("gopRemainingBipredictive"));
	private static final long gopRemainingBipredictive$OFFSET =
			$LAYOUT.byteOffset(groupElement("gopRemainingBipredictive"));

	VkVideoEncodeAV1GopRemainingFrameInfoKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 useGopRemainingFrames
	 *}
	 */
	public static final OfInt useGopRemainingFrames$layout()
	{
		return useGopRemainingFrames$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 useGopRemainingFrames
	 *}
	 */
	public static final long useGopRemainingFrames$offset()
	{
		return useGopRemainingFrames$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 useGopRemainingFrames
	 *}
	 */
	public static int useGopRemainingFrames(MemorySegment struct)
	{
		return struct.get(useGopRemainingFrames$LAYOUT, useGopRemainingFrames$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 useGopRemainingFrames
	 *}
	 */
	public static void useGopRemainingFrames(MemorySegment struct, int fieldValue)
	{
		struct.set(useGopRemainingFrames$LAYOUT, useGopRemainingFrames$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingIntra
	 *}
	 */
	public static final OfInt gopRemainingIntra$layout()
	{
		return gopRemainingIntra$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingIntra
	 *}
	 */
	public static final long gopRemainingIntra$offset()
	{
		return gopRemainingIntra$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingIntra
	 *}
	 */
	public static int gopRemainingIntra(MemorySegment struct)
	{
		return struct.get(gopRemainingIntra$LAYOUT, gopRemainingIntra$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingIntra
	 *}
	 */
	public static void gopRemainingIntra(MemorySegment struct, int fieldValue)
	{
		struct.set(gopRemainingIntra$LAYOUT, gopRemainingIntra$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingPredictive
	 *}
	 */
	public static final OfInt gopRemainingPredictive$layout()
	{
		return gopRemainingPredictive$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingPredictive
	 *}
	 */
	public static final long gopRemainingPredictive$offset()
	{
		return gopRemainingPredictive$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingPredictive
	 *}
	 */
	public static int gopRemainingPredictive(MemorySegment struct)
	{
		return struct.get(gopRemainingPredictive$LAYOUT, gopRemainingPredictive$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingPredictive
	 *}
	 */
	public static void gopRemainingPredictive(MemorySegment struct, int fieldValue)
	{
		struct.set(gopRemainingPredictive$LAYOUT, gopRemainingPredictive$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingBipredictive
	 *}
	 */
	public static final OfInt gopRemainingBipredictive$layout()
	{
		return gopRemainingBipredictive$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingBipredictive
	 *}
	 */
	public static final long gopRemainingBipredictive$offset()
	{
		return gopRemainingBipredictive$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingBipredictive
	 *}
	 */
	public static int gopRemainingBipredictive(MemorySegment struct)
	{
		return struct.get(gopRemainingBipredictive$LAYOUT, gopRemainingBipredictive$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t gopRemainingBipredictive
	 *}
	 */
	public static void gopRemainingBipredictive(MemorySegment struct, int fieldValue)
	{
		struct.set(gopRemainingBipredictive$LAYOUT, gopRemainingBipredictive$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

