// Generated by jextract

package vulkan;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c:
 * typedef VkResult (*PFN_vkCreateShadersEXT)(VkDevice, uint32_t, const VkShaderCreateInfoEXT *, const VkAllocationCallbacks *, VkShaderEXT *) __attribute__((stdcall))
 *}
 */
public final class PFN_vkCreateShadersEXT
{

	private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
			Vulkan.C_INT,
			Vulkan.C_POINTER,
			Vulkan.C_INT,
			Vulkan.C_POINTER,
			Vulkan.C_POINTER,
			Vulkan.C_POINTER
	);
	private static final MethodHandle UP$MH =
			Vulkan.upcallHandle(PFN_vkCreateShadersEXT.Function.class, "apply", $DESC);
	private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

	private PFN_vkCreateShadersEXT()
	{
		// Should not be called directly
	}

	/**
	 * The descriptor of this function pointer
	 */
	public static FunctionDescriptor descriptor()
	{
		return $DESC;
	}

	/**
	 * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
	 * is managed by {@code arena}
	 */
	public static MemorySegment allocate(PFN_vkCreateShadersEXT.Function fi, Arena arena)
	{
		return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
	}

	/**
	 * Invoke the upcall stub {@code funcPtr}, with given parameters
	 */
	public static int invoke(MemorySegment funcPtr, MemorySegment device, int createInfoCount,
							 MemorySegment pCreateInfos, MemorySegment pAllocator, MemorySegment pShaders)
	{
		try
		{
			return (int) DOWN$MH.invokeExact(funcPtr, device, createInfoCount, pCreateInfos, pAllocator, pShaders);
		} catch (Error | RuntimeException ex)
		{
			throw ex;
		} catch (Throwable ex$)
		{
			throw new AssertionError("should not reach here", ex$);
		}
	}

	/**
	 * The function pointer signature, expressed as a functional interface
	 */
	public interface Function
	{
		int apply(MemorySegment device, int createInfoCount, MemorySegment pCreateInfos, MemorySegment pAllocator,
				  MemorySegment pShaders);
	}
}

