// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkBindBufferMemoryDeviceGroupInfo VkBindBufferMemoryDeviceGroupInfoKHR
 *}
 */
public class VkBindBufferMemoryDeviceGroupInfoKHR extends VkBindBufferMemoryDeviceGroupInfo
{

	VkBindBufferMemoryDeviceGroupInfoKHR()
	{
		// Should not be called directly
	}
}

