// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkBindDescriptorSetsInfo VkBindDescriptorSetsInfoKHR
 *}
 */
public class VkBindDescriptorSetsInfoKHR extends VkBindDescriptorSetsInfo
{

	VkBindDescriptorSetsInfoKHR()
	{
		// Should not be called directly
	}
}

