// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkCommandBufferSubmitInfo VkCommandBufferSubmitInfoKHR
 *}
 */
public class VkCommandBufferSubmitInfoKHR extends VkCommandBufferSubmitInfo
{

	VkCommandBufferSubmitInfoKHR()
	{
		// Should not be called directly
	}
}

