// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkDrawMeshTasksIndirectCommandEXT {
 *     uint32_t groupCountX;
 *     uint32_t groupCountY;
 *     uint32_t groupCountZ;
 * }
 *}
 */
public class VkDrawMeshTasksIndirectCommandEXT
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("groupCountX"),
			Vulkan.C_INT.withName("groupCountY"),
			Vulkan.C_INT.withName("groupCountZ")
	).withName("VkDrawMeshTasksIndirectCommandEXT");
	private static final OfInt groupCountX$LAYOUT = (OfInt) $LAYOUT.select(groupElement("groupCountX"));
	private static final long groupCountX$OFFSET = $LAYOUT.byteOffset(groupElement("groupCountX"));
	private static final OfInt groupCountY$LAYOUT = (OfInt) $LAYOUT.select(groupElement("groupCountY"));
	private static final long groupCountY$OFFSET = $LAYOUT.byteOffset(groupElement("groupCountY"));
	private static final OfInt groupCountZ$LAYOUT = (OfInt) $LAYOUT.select(groupElement("groupCountZ"));
	private static final long groupCountZ$OFFSET = $LAYOUT.byteOffset(groupElement("groupCountZ"));

	VkDrawMeshTasksIndirectCommandEXT()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountX
	 *}
	 */
	public static final OfInt groupCountX$layout()
	{
		return groupCountX$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountX
	 *}
	 */
	public static final long groupCountX$offset()
	{
		return groupCountX$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountX
	 *}
	 */
	public static int groupCountX(MemorySegment struct)
	{
		return struct.get(groupCountX$LAYOUT, groupCountX$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountX
	 *}
	 */
	public static void groupCountX(MemorySegment struct, int fieldValue)
	{
		struct.set(groupCountX$LAYOUT, groupCountX$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountY
	 *}
	 */
	public static final OfInt groupCountY$layout()
	{
		return groupCountY$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountY
	 *}
	 */
	public static final long groupCountY$offset()
	{
		return groupCountY$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountY
	 *}
	 */
	public static int groupCountY(MemorySegment struct)
	{
		return struct.get(groupCountY$LAYOUT, groupCountY$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountY
	 *}
	 */
	public static void groupCountY(MemorySegment struct, int fieldValue)
	{
		struct.set(groupCountY$LAYOUT, groupCountY$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountZ
	 *}
	 */
	public static final OfInt groupCountZ$layout()
	{
		return groupCountZ$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountZ
	 *}
	 */
	public static final long groupCountZ$offset()
	{
		return groupCountZ$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountZ
	 *}
	 */
	public static int groupCountZ(MemorySegment struct)
	{
		return struct.get(groupCountZ$LAYOUT, groupCountZ$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t groupCountZ
	 *}
	 */
	public static void groupCountZ(MemorySegment struct, int fieldValue)
	{
		struct.set(groupCountZ$LAYOUT, groupCountZ$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

