// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkImageBlit2 VkImageBlit2KHR
 *}
 */
public class VkImageBlit2KHR extends VkImageBlit2
{

	VkImageBlit2KHR()
	{
		// Should not be called directly
	}
}

