// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkImageSubresource2 VkImageSubresource2EXT
 *}
 */
public class VkImageSubresource2EXT extends VkImageSubresource2
{

	VkImageSubresource2EXT()
	{
		// Should not be called directly
	}
}

