// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkIndirectCommandsVertexBufferTokenEXT {
 *     uint32_t vertexBindingUnit;
 * }
 *}
 */
public class VkIndirectCommandsVertexBufferTokenEXT
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("vertexBindingUnit")
	).withName("VkIndirectCommandsVertexBufferTokenEXT");
	private static final OfInt vertexBindingUnit$LAYOUT = (OfInt) $LAYOUT.select(groupElement("vertexBindingUnit"));
	private static final long vertexBindingUnit$OFFSET = $LAYOUT.byteOffset(groupElement("vertexBindingUnit"));

	VkIndirectCommandsVertexBufferTokenEXT()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t vertexBindingUnit
	 *}
	 */
	public static final OfInt vertexBindingUnit$layout()
	{
		return vertexBindingUnit$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t vertexBindingUnit
	 *}
	 */
	public static final long vertexBindingUnit$offset()
	{
		return vertexBindingUnit$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t vertexBindingUnit
	 *}
	 */
	public static int vertexBindingUnit(MemorySegment struct)
	{
		return struct.get(vertexBindingUnit$LAYOUT, vertexBindingUnit$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t vertexBindingUnit
	 *}
	 */
	public static void vertexBindingUnit(MemorySegment struct, int fieldValue)
	{
		struct.set(vertexBindingUnit$LAYOUT, vertexBindingUnit$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

