// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkMutableDescriptorTypeListEXT VkMutableDescriptorTypeListVALVE
 *}
 */
public class VkMutableDescriptorTypeListVALVE extends VkMutableDescriptorTypeListEXT
{

	VkMutableDescriptorTypeListVALVE()
	{
		// Should not be called directly
	}
}

