// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDevicePerformanceCountersByRegionPropertiesARM {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t maxPerRegionPerformanceCounters;
 *     VkExtent2D performanceCounterRegionSize;
 *     uint32_t rowStrideAlignment;
 *     uint32_t regionAlignment;
 *     VkBool32 identityTransformOrder;
 * }
 *}
 */
public class VkPhysicalDevicePerformanceCountersByRegionPropertiesARM
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("maxPerRegionPerformanceCounters"),
			VkExtent2D.layout().withName("performanceCounterRegionSize"),
			Vulkan.C_INT.withName("rowStrideAlignment"),
			Vulkan.C_INT.withName("regionAlignment"),
			Vulkan.C_INT.withName("identityTransformOrder")
	).withName("VkPhysicalDevicePerformanceCountersByRegionPropertiesARM");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt maxPerRegionPerformanceCounters$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxPerRegionPerformanceCounters"));
	private static final long maxPerRegionPerformanceCounters$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxPerRegionPerformanceCounters"));
	private static final GroupLayout performanceCounterRegionSize$LAYOUT =
			(GroupLayout) $LAYOUT.select(groupElement("performanceCounterRegionSize"));
	private static final long performanceCounterRegionSize$OFFSET =
			$LAYOUT.byteOffset(groupElement("performanceCounterRegionSize"));
	private static final OfInt rowStrideAlignment$LAYOUT = (OfInt) $LAYOUT.select(groupElement("rowStrideAlignment"));
	private static final long rowStrideAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("rowStrideAlignment"));
	private static final OfInt regionAlignment$LAYOUT = (OfInt) $LAYOUT.select(groupElement("regionAlignment"));
	private static final long regionAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("regionAlignment"));
	private static final OfInt identityTransformOrder$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("identityTransformOrder"));
	private static final long identityTransformOrder$OFFSET =
			$LAYOUT.byteOffset(groupElement("identityTransformOrder"));

	VkPhysicalDevicePerformanceCountersByRegionPropertiesARM()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerRegionPerformanceCounters
	 *}
	 */
	public static final OfInt maxPerRegionPerformanceCounters$layout()
	{
		return maxPerRegionPerformanceCounters$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerRegionPerformanceCounters
	 *}
	 */
	public static final long maxPerRegionPerformanceCounters$offset()
	{
		return maxPerRegionPerformanceCounters$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerRegionPerformanceCounters
	 *}
	 */
	public static int maxPerRegionPerformanceCounters(MemorySegment struct)
	{
		return struct.get(maxPerRegionPerformanceCounters$LAYOUT, maxPerRegionPerformanceCounters$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerRegionPerformanceCounters
	 *}
	 */
	public static void maxPerRegionPerformanceCounters(MemorySegment struct, int fieldValue)
	{
		struct.set(maxPerRegionPerformanceCounters$LAYOUT, maxPerRegionPerformanceCounters$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkExtent2D performanceCounterRegionSize
	 *}
	 */
	public static final GroupLayout performanceCounterRegionSize$layout()
	{
		return performanceCounterRegionSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkExtent2D performanceCounterRegionSize
	 *}
	 */
	public static final long performanceCounterRegionSize$offset()
	{
		return performanceCounterRegionSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkExtent2D performanceCounterRegionSize
	 *}
	 */
	public static MemorySegment performanceCounterRegionSize(MemorySegment struct)
	{
		return struct.asSlice(performanceCounterRegionSize$OFFSET, performanceCounterRegionSize$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkExtent2D performanceCounterRegionSize
	 *}
	 */
	public static void performanceCounterRegionSize(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, performanceCounterRegionSize$OFFSET,
				performanceCounterRegionSize$LAYOUT.byteSize());
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t rowStrideAlignment
	 *}
	 */
	public static final OfInt rowStrideAlignment$layout()
	{
		return rowStrideAlignment$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t rowStrideAlignment
	 *}
	 */
	public static final long rowStrideAlignment$offset()
	{
		return rowStrideAlignment$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t rowStrideAlignment
	 *}
	 */
	public static int rowStrideAlignment(MemorySegment struct)
	{
		return struct.get(rowStrideAlignment$LAYOUT, rowStrideAlignment$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t rowStrideAlignment
	 *}
	 */
	public static void rowStrideAlignment(MemorySegment struct, int fieldValue)
	{
		struct.set(rowStrideAlignment$LAYOUT, rowStrideAlignment$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t regionAlignment
	 *}
	 */
	public static final OfInt regionAlignment$layout()
	{
		return regionAlignment$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t regionAlignment
	 *}
	 */
	public static final long regionAlignment$offset()
	{
		return regionAlignment$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t regionAlignment
	 *}
	 */
	public static int regionAlignment(MemorySegment struct)
	{
		return struct.get(regionAlignment$LAYOUT, regionAlignment$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t regionAlignment
	 *}
	 */
	public static void regionAlignment(MemorySegment struct, int fieldValue)
	{
		struct.set(regionAlignment$LAYOUT, regionAlignment$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 identityTransformOrder
	 *}
	 */
	public static final OfInt identityTransformOrder$layout()
	{
		return identityTransformOrder$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 identityTransformOrder
	 *}
	 */
	public static final long identityTransformOrder$offset()
	{
		return identityTransformOrder$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 identityTransformOrder
	 *}
	 */
	public static int identityTransformOrder(MemorySegment struct)
	{
		return struct.get(identityTransformOrder$LAYOUT, identityTransformOrder$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 identityTransformOrder
	 *}
	 */
	public static void identityTransformOrder(MemorySegment struct, int fieldValue)
	{
		struct.set(identityTransformOrder$LAYOUT, identityTransformOrder$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

