// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang = c:
 * struct VkPhysicalDeviceTensorPropertiesARM {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t maxTensorDimensionCount;
 *     uint64_t maxTensorElements;
 *     uint64_t maxPerDimensionTensorElements;
 *     int64_t maxTensorStride;
 *     uint64_t maxTensorSize;
 *     uint32_t maxTensorShaderAccessArrayLength;
 *     uint32_t maxTensorShaderAccessSize;
 *     uint32_t maxDescriptorSetStorageTensors;
 *     uint32_t maxPerStageDescriptorSetStorageTensors;
 *     uint32_t maxDescriptorSetUpdateAfterBindStorageTensors;
 *     uint32_t maxPerStageDescriptorUpdateAfterBindStorageTensors;
 *     VkBool32 shaderStorageTensorArrayNonUniformIndexingNative;
 *     VkShaderStageFlags shaderTensorSupportedStages;
 * }
 *}
 */
public class VkPhysicalDeviceTensorPropertiesARM
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("maxTensorDimensionCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_LONG_LONG.withName("maxTensorElements"),
			Vulkan.C_LONG_LONG.withName("maxPerDimensionTensorElements"),
			Vulkan.C_LONG_LONG.withName("maxTensorStride"),
			Vulkan.C_LONG_LONG.withName("maxTensorSize"),
			Vulkan.C_INT.withName("maxTensorShaderAccessArrayLength"),
			Vulkan.C_INT.withName("maxTensorShaderAccessSize"),
			Vulkan.C_INT.withName("maxDescriptorSetStorageTensors"),
			Vulkan.C_INT.withName("maxPerStageDescriptorSetStorageTensors"),
			Vulkan.C_INT.withName("maxDescriptorSetUpdateAfterBindStorageTensors"),
			Vulkan.C_INT.withName("maxPerStageDescriptorUpdateAfterBindStorageTensors"),
			Vulkan.C_INT.withName("shaderStorageTensorArrayNonUniformIndexingNative"),
			Vulkan.C_INT.withName("shaderTensorSupportedStages")
	).withName("VkPhysicalDeviceTensorPropertiesARM");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt maxTensorDimensionCount$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxTensorDimensionCount"));
	private static final long maxTensorDimensionCount$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxTensorDimensionCount"));
	private static final OfLong maxTensorElements$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxTensorElements"));
	private static final long maxTensorElements$OFFSET = $LAYOUT.byteOffset(groupElement("maxTensorElements"));
	private static final OfLong maxPerDimensionTensorElements$LAYOUT =
			(OfLong) $LAYOUT.select(groupElement("maxPerDimensionTensorElements"));
	private static final long maxPerDimensionTensorElements$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxPerDimensionTensorElements"));
	private static final OfLong maxTensorStride$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxTensorStride"));
	private static final long maxTensorStride$OFFSET = $LAYOUT.byteOffset(groupElement("maxTensorStride"));
	private static final OfLong maxTensorSize$LAYOUT = (OfLong) $LAYOUT.select(groupElement("maxTensorSize"));
	private static final long maxTensorSize$OFFSET = $LAYOUT.byteOffset(groupElement("maxTensorSize"));
	private static final OfInt maxTensorShaderAccessArrayLength$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxTensorShaderAccessArrayLength"));
	private static final long maxTensorShaderAccessArrayLength$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxTensorShaderAccessArrayLength"));
	private static final OfInt maxTensorShaderAccessSize$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxTensorShaderAccessSize"));
	private static final long maxTensorShaderAccessSize$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxTensorShaderAccessSize"));
	private static final OfInt maxDescriptorSetStorageTensors$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxDescriptorSetStorageTensors"));
	private static final long maxDescriptorSetStorageTensors$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxDescriptorSetStorageTensors"));
	private static final OfInt maxPerStageDescriptorSetStorageTensors$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxPerStageDescriptorSetStorageTensors"));
	private static final long maxPerStageDescriptorSetStorageTensors$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxPerStageDescriptorSetStorageTensors"));
	private static final OfInt maxDescriptorSetUpdateAfterBindStorageTensors$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxDescriptorSetUpdateAfterBindStorageTensors"));
	private static final long maxDescriptorSetUpdateAfterBindStorageTensors$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxDescriptorSetUpdateAfterBindStorageTensors"));
	private static final OfInt maxPerStageDescriptorUpdateAfterBindStorageTensors$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("maxPerStageDescriptorUpdateAfterBindStorageTensors"));
	private static final long maxPerStageDescriptorUpdateAfterBindStorageTensors$OFFSET =
			$LAYOUT.byteOffset(groupElement("maxPerStageDescriptorUpdateAfterBindStorageTensors"));
	private static final OfInt shaderStorageTensorArrayNonUniformIndexingNative$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderStorageTensorArrayNonUniformIndexingNative"));
	private static final long shaderStorageTensorArrayNonUniformIndexingNative$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderStorageTensorArrayNonUniformIndexingNative"));
	private static final OfInt shaderTensorSupportedStages$LAYOUT =
			(OfInt) $LAYOUT.select(groupElement("shaderTensorSupportedStages"));
	private static final long shaderTensorSupportedStages$OFFSET =
			$LAYOUT.byteOffset(groupElement("shaderTensorSupportedStages"));

	VkPhysicalDeviceTensorPropertiesARM()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorDimensionCount
	 *}
	 */
	public static final OfInt maxTensorDimensionCount$layout()
	{
		return maxTensorDimensionCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorDimensionCount
	 *}
	 */
	public static final long maxTensorDimensionCount$offset()
	{
		return maxTensorDimensionCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorDimensionCount
	 *}
	 */
	public static int maxTensorDimensionCount(MemorySegment struct)
	{
		return struct.get(maxTensorDimensionCount$LAYOUT, maxTensorDimensionCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorDimensionCount
	 *}
	 */
	public static void maxTensorDimensionCount(MemorySegment struct, int fieldValue)
	{
		struct.set(maxTensorDimensionCount$LAYOUT, maxTensorDimensionCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorElements
	 *}
	 */
	public static final OfLong maxTensorElements$layout()
	{
		return maxTensorElements$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorElements
	 *}
	 */
	public static final long maxTensorElements$offset()
	{
		return maxTensorElements$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorElements
	 *}
	 */
	public static long maxTensorElements(MemorySegment struct)
	{
		return struct.get(maxTensorElements$LAYOUT, maxTensorElements$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorElements
	 *}
	 */
	public static void maxTensorElements(MemorySegment struct, long fieldValue)
	{
		struct.set(maxTensorElements$LAYOUT, maxTensorElements$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxPerDimensionTensorElements
	 *}
	 */
	public static final OfLong maxPerDimensionTensorElements$layout()
	{
		return maxPerDimensionTensorElements$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxPerDimensionTensorElements
	 *}
	 */
	public static final long maxPerDimensionTensorElements$offset()
	{
		return maxPerDimensionTensorElements$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxPerDimensionTensorElements
	 *}
	 */
	public static long maxPerDimensionTensorElements(MemorySegment struct)
	{
		return struct.get(maxPerDimensionTensorElements$LAYOUT, maxPerDimensionTensorElements$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxPerDimensionTensorElements
	 *}
	 */
	public static void maxPerDimensionTensorElements(MemorySegment struct, long fieldValue)
	{
		struct.set(maxPerDimensionTensorElements$LAYOUT, maxPerDimensionTensorElements$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * int64_t maxTensorStride
	 *}
	 */
	public static final OfLong maxTensorStride$layout()
	{
		return maxTensorStride$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * int64_t maxTensorStride
	 *}
	 */
	public static final long maxTensorStride$offset()
	{
		return maxTensorStride$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * int64_t maxTensorStride
	 *}
	 */
	public static long maxTensorStride(MemorySegment struct)
	{
		return struct.get(maxTensorStride$LAYOUT, maxTensorStride$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * int64_t maxTensorStride
	 *}
	 */
	public static void maxTensorStride(MemorySegment struct, long fieldValue)
	{
		struct.set(maxTensorStride$LAYOUT, maxTensorStride$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorSize
	 *}
	 */
	public static final OfLong maxTensorSize$layout()
	{
		return maxTensorSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorSize
	 *}
	 */
	public static final long maxTensorSize$offset()
	{
		return maxTensorSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorSize
	 *}
	 */
	public static long maxTensorSize(MemorySegment struct)
	{
		return struct.get(maxTensorSize$LAYOUT, maxTensorSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint64_t maxTensorSize
	 *}
	 */
	public static void maxTensorSize(MemorySegment struct, long fieldValue)
	{
		struct.set(maxTensorSize$LAYOUT, maxTensorSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessArrayLength
	 *}
	 */
	public static final OfInt maxTensorShaderAccessArrayLength$layout()
	{
		return maxTensorShaderAccessArrayLength$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessArrayLength
	 *}
	 */
	public static final long maxTensorShaderAccessArrayLength$offset()
	{
		return maxTensorShaderAccessArrayLength$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessArrayLength
	 *}
	 */
	public static int maxTensorShaderAccessArrayLength(MemorySegment struct)
	{
		return struct.get(maxTensorShaderAccessArrayLength$LAYOUT, maxTensorShaderAccessArrayLength$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessArrayLength
	 *}
	 */
	public static void maxTensorShaderAccessArrayLength(MemorySegment struct, int fieldValue)
	{
		struct.set(maxTensorShaderAccessArrayLength$LAYOUT, maxTensorShaderAccessArrayLength$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessSize
	 *}
	 */
	public static final OfInt maxTensorShaderAccessSize$layout()
	{
		return maxTensorShaderAccessSize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessSize
	 *}
	 */
	public static final long maxTensorShaderAccessSize$offset()
	{
		return maxTensorShaderAccessSize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessSize
	 *}
	 */
	public static int maxTensorShaderAccessSize(MemorySegment struct)
	{
		return struct.get(maxTensorShaderAccessSize$LAYOUT, maxTensorShaderAccessSize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxTensorShaderAccessSize
	 *}
	 */
	public static void maxTensorShaderAccessSize(MemorySegment struct, int fieldValue)
	{
		struct.set(maxTensorShaderAccessSize$LAYOUT, maxTensorShaderAccessSize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetStorageTensors
	 *}
	 */
	public static final OfInt maxDescriptorSetStorageTensors$layout()
	{
		return maxDescriptorSetStorageTensors$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetStorageTensors
	 *}
	 */
	public static final long maxDescriptorSetStorageTensors$offset()
	{
		return maxDescriptorSetStorageTensors$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetStorageTensors
	 *}
	 */
	public static int maxDescriptorSetStorageTensors(MemorySegment struct)
	{
		return struct.get(maxDescriptorSetStorageTensors$LAYOUT, maxDescriptorSetStorageTensors$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetStorageTensors
	 *}
	 */
	public static void maxDescriptorSetStorageTensors(MemorySegment struct, int fieldValue)
	{
		struct.set(maxDescriptorSetStorageTensors$LAYOUT, maxDescriptorSetStorageTensors$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorSetStorageTensors
	 *}
	 */
	public static final OfInt maxPerStageDescriptorSetStorageTensors$layout()
	{
		return maxPerStageDescriptorSetStorageTensors$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorSetStorageTensors
	 *}
	 */
	public static final long maxPerStageDescriptorSetStorageTensors$offset()
	{
		return maxPerStageDescriptorSetStorageTensors$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorSetStorageTensors
	 *}
	 */
	public static int maxPerStageDescriptorSetStorageTensors(MemorySegment struct)
	{
		return struct.get(maxPerStageDescriptorSetStorageTensors$LAYOUT, maxPerStageDescriptorSetStorageTensors$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorSetStorageTensors
	 *}
	 */
	public static void maxPerStageDescriptorSetStorageTensors(MemorySegment struct, int fieldValue)
	{
		struct.set(maxPerStageDescriptorSetStorageTensors$LAYOUT, maxPerStageDescriptorSetStorageTensors$OFFSET,
				fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetUpdateAfterBindStorageTensors
	 *}
	 */
	public static final OfInt maxDescriptorSetUpdateAfterBindStorageTensors$layout()
	{
		return maxDescriptorSetUpdateAfterBindStorageTensors$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetUpdateAfterBindStorageTensors
	 *}
	 */
	public static final long maxDescriptorSetUpdateAfterBindStorageTensors$offset()
	{
		return maxDescriptorSetUpdateAfterBindStorageTensors$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetUpdateAfterBindStorageTensors
	 *}
	 */
	public static int maxDescriptorSetUpdateAfterBindStorageTensors(MemorySegment struct)
	{
		return struct.get(maxDescriptorSetUpdateAfterBindStorageTensors$LAYOUT,
				maxDescriptorSetUpdateAfterBindStorageTensors$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxDescriptorSetUpdateAfterBindStorageTensors
	 *}
	 */
	public static void maxDescriptorSetUpdateAfterBindStorageTensors(MemorySegment struct, int fieldValue)
	{
		struct.set(maxDescriptorSetUpdateAfterBindStorageTensors$LAYOUT,
				maxDescriptorSetUpdateAfterBindStorageTensors$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorUpdateAfterBindStorageTensors
	 *}
	 */
	public static final OfInt maxPerStageDescriptorUpdateAfterBindStorageTensors$layout()
	{
		return maxPerStageDescriptorUpdateAfterBindStorageTensors$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorUpdateAfterBindStorageTensors
	 *}
	 */
	public static final long maxPerStageDescriptorUpdateAfterBindStorageTensors$offset()
	{
		return maxPerStageDescriptorUpdateAfterBindStorageTensors$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorUpdateAfterBindStorageTensors
	 *}
	 */
	public static int maxPerStageDescriptorUpdateAfterBindStorageTensors(MemorySegment struct)
	{
		return struct.get(maxPerStageDescriptorUpdateAfterBindStorageTensors$LAYOUT,
				maxPerStageDescriptorUpdateAfterBindStorageTensors$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t maxPerStageDescriptorUpdateAfterBindStorageTensors
	 *}
	 */
	public static void maxPerStageDescriptorUpdateAfterBindStorageTensors(MemorySegment struct, int fieldValue)
	{
		struct.set(maxPerStageDescriptorUpdateAfterBindStorageTensors$LAYOUT,
				maxPerStageDescriptorUpdateAfterBindStorageTensors$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTensorArrayNonUniformIndexingNative
	 *}
	 */
	public static final OfInt shaderStorageTensorArrayNonUniformIndexingNative$layout()
	{
		return shaderStorageTensorArrayNonUniformIndexingNative$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTensorArrayNonUniformIndexingNative
	 *}
	 */
	public static final long shaderStorageTensorArrayNonUniformIndexingNative$offset()
	{
		return shaderStorageTensorArrayNonUniformIndexingNative$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTensorArrayNonUniformIndexingNative
	 *}
	 */
	public static int shaderStorageTensorArrayNonUniformIndexingNative(MemorySegment struct)
	{
		return struct.get(shaderStorageTensorArrayNonUniformIndexingNative$LAYOUT,
				shaderStorageTensorArrayNonUniformIndexingNative$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkBool32 shaderStorageTensorArrayNonUniformIndexingNative
	 *}
	 */
	public static void shaderStorageTensorArrayNonUniformIndexingNative(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderStorageTensorArrayNonUniformIndexingNative$LAYOUT,
				shaderStorageTensorArrayNonUniformIndexingNative$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkShaderStageFlags shaderTensorSupportedStages
	 *}
	 */
	public static final OfInt shaderTensorSupportedStages$layout()
	{
		return shaderTensorSupportedStages$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkShaderStageFlags shaderTensorSupportedStages
	 *}
	 */
	public static final long shaderTensorSupportedStages$offset()
	{
		return shaderTensorSupportedStages$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkShaderStageFlags shaderTensorSupportedStages
	 *}
	 */
	public static int shaderTensorSupportedStages(MemorySegment struct)
	{
		return struct.get(shaderTensorSupportedStages$LAYOUT, shaderTensorSupportedStages$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkShaderStageFlags shaderTensorSupportedStages
	 *}
	 */
	public static void shaderTensorSupportedStages(MemorySegment struct, int fieldValue)
	{
		struct.set(shaderTensorSupportedStages$LAYOUT, shaderTensorSupportedStages$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

