// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.MemoryLayout.PathElement.sequenceElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkPipelineBinaryKeyKHR {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t keySize;
 *     uint8_t key[32];
 * }
 *}
 */
public class VkPipelineBinaryKeyKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("keySize"),
			MemoryLayout.sequenceLayout(32, Vulkan.C_CHAR).withName("key"),
			MemoryLayout.paddingLayout(4)
	).withName("VkPipelineBinaryKeyKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt keySize$LAYOUT = (OfInt) $LAYOUT.select(groupElement("keySize"));
	private static final long keySize$OFFSET = $LAYOUT.byteOffset(groupElement("keySize"));
	private static final SequenceLayout key$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("key"));
	private static final VarHandle key$ELEM_HANDLE = key$LAYOUT.varHandle(sequenceElement());
	private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));
	private static long[] key$DIMS = {32};

	VkPipelineBinaryKeyKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t keySize
	 *}
	 */
	public static final OfInt keySize$layout()
	{
		return keySize$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t keySize
	 *}
	 */
	public static final long keySize$offset()
	{
		return keySize$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t keySize
	 *}
	 */
	public static int keySize(MemorySegment struct)
	{
		return struct.get(keySize$LAYOUT, keySize$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t keySize
	 *}
	 */
	public static void keySize(MemorySegment struct, int fieldValue)
	{
		struct.set(keySize$LAYOUT, keySize$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static final SequenceLayout key$layout()
	{
		return key$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static final long key$offset()
	{
		return key$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static MemorySegment key(MemorySegment struct)
	{
		return struct.asSlice(key$OFFSET, key$LAYOUT.byteSize());
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static void key(MemorySegment struct, MemorySegment fieldValue)
	{
		MemorySegment.copy(fieldValue, 0L, struct, key$OFFSET, key$LAYOUT.byteSize());
	}

	/**
	 * Dimensions for array field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static long[] key$dimensions()
	{
		return key$DIMS;
	}

	/**
	 * Indexed getter for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static byte key(MemorySegment struct, long index0)
	{
		return (byte) key$ELEM_HANDLE.get(struct, key$OFFSET, index0);
	}

	/**
	 * Indexed setter for field:
	 * {@snippet lang = c:
	 * uint8_t key[32]
	 *}
	 */
	public static void key(MemorySegment struct, long index0, byte fieldValue)
	{
		key$ELEM_HANDLE.set(struct, key$OFFSET, index0, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

