// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkPipelineBinaryInfoKHR {
 *     VkStructureType sType;
 *     const void *pNext;
 *     uint32_t binaryCount;
 *     const VkPipelineBinaryKHR *pPipelineBinaries;
 * }
 *}
 */
public class VkPipelineBinaryInfoKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_INT.withName("binaryCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pPipelineBinaries")
	).withName("VkPipelineBinaryInfoKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final OfInt binaryCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("binaryCount"));
	private static final long binaryCount$OFFSET = $LAYOUT.byteOffset(groupElement("binaryCount"));
	private static final AddressLayout pPipelineBinaries$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pPipelineBinaries"));
	private static final long pPipelineBinaries$OFFSET = $LAYOUT.byteOffset(groupElement("pPipelineBinaries"));

	VkPipelineBinaryInfoKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t binaryCount
	 *}
	 */
	public static final OfInt binaryCount$layout()
	{
		return binaryCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t binaryCount
	 *}
	 */
	public static final long binaryCount$offset()
	{
		return binaryCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t binaryCount
	 *}
	 */
	public static int binaryCount(MemorySegment struct)
	{
		return struct.get(binaryCount$LAYOUT, binaryCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t binaryCount
	 *}
	 */
	public static void binaryCount(MemorySegment struct, int fieldValue)
	{
		struct.set(binaryCount$LAYOUT, binaryCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const VkPipelineBinaryKHR *pPipelineBinaries
	 *}
	 */
	public static final AddressLayout pPipelineBinaries$layout()
	{
		return pPipelineBinaries$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const VkPipelineBinaryKHR *pPipelineBinaries
	 *}
	 */
	public static final long pPipelineBinaries$offset()
	{
		return pPipelineBinaries$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const VkPipelineBinaryKHR *pPipelineBinaries
	 *}
	 */
	public static MemorySegment pPipelineBinaries(MemorySegment struct)
	{
		return struct.get(pPipelineBinaries$LAYOUT, pPipelineBinaries$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const VkPipelineBinaryKHR *pPipelineBinaries
	 *}
	 */
	public static void pPipelineBinaries(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pPipelineBinaries$LAYOUT, pPipelineBinaries$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

