// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkQueryPoolPerformanceQueryCreateInfoINTEL VkQueryPoolCreateInfoINTEL
 *}
 */
public class VkQueryPoolCreateInfoINTEL extends VkQueryPoolPerformanceQueryCreateInfoINTEL
{

	VkQueryPoolCreateInfoINTEL()
	{
		// Should not be called directly
	}
}

