// Generated by jextract

package vulkan;

/**
 * {@snippet lang = c:
 * typedef VkRenderingInputAttachmentIndexInfo VkRenderingInputAttachmentIndexInfoKHR
 *}
 */
public class VkRenderingInputAttachmentIndexInfoKHR extends VkRenderingInputAttachmentIndexInfo
{

	VkRenderingInputAttachmentIndexInfoKHR()
	{
		// Should not be called directly
	}
}

