// Generated by jextract

package vulkan;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;

/**
 * {@snippet lang = c:
 * struct VkVideoDecodeH265PictureInfoKHR {
 *     VkStructureType sType;
 *     const void *pNext;
 *     const StdVideoDecodeH265PictureInfo *pStdPictureInfo;
 *     uint32_t sliceSegmentCount;
 *     const uint32_t *pSliceSegmentOffsets;
 * }
 *}
 */
public class VkVideoDecodeH265PictureInfoKHR
{

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
			Vulkan.C_INT.withName("sType"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pNext"),
			Vulkan.C_POINTER.withName("pStdPictureInfo"),
			Vulkan.C_INT.withName("sliceSegmentCount"),
			MemoryLayout.paddingLayout(4),
			Vulkan.C_POINTER.withName("pSliceSegmentOffsets")
	).withName("VkVideoDecodeH265PictureInfoKHR");
	private static final OfInt sType$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sType"));
	private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));
	private static final AddressLayout pNext$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("pNext"));
	private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));
	private static final AddressLayout pStdPictureInfo$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pStdPictureInfo"));
	private static final long pStdPictureInfo$OFFSET = $LAYOUT.byteOffset(groupElement("pStdPictureInfo"));
	private static final OfInt sliceSegmentCount$LAYOUT = (OfInt) $LAYOUT.select(groupElement("sliceSegmentCount"));
	private static final long sliceSegmentCount$OFFSET = $LAYOUT.byteOffset(groupElement("sliceSegmentCount"));
	private static final AddressLayout pSliceSegmentOffsets$LAYOUT =
			(AddressLayout) $LAYOUT.select(groupElement("pSliceSegmentOffsets"));
	private static final long pSliceSegmentOffsets$OFFSET = $LAYOUT.byteOffset(groupElement("pSliceSegmentOffsets"));

	VkVideoDecodeH265PictureInfoKHR()
	{
		// Should not be called directly
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final OfInt sType$layout()
	{
		return sType$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static final long sType$offset()
	{
		return sType$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static int sType(MemorySegment struct)
	{
		return struct.get(sType$LAYOUT, sType$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * VkStructureType sType
	 *}
	 */
	public static void sType(MemorySegment struct, int fieldValue)
	{
		struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final AddressLayout pNext$layout()
	{
		return pNext$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static final long pNext$offset()
	{
		return pNext$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static MemorySegment pNext(MemorySegment struct)
	{
		return struct.get(pNext$LAYOUT, pNext$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const void *pNext
	 *}
	 */
	public static void pNext(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const StdVideoDecodeH265PictureInfo *pStdPictureInfo
	 *}
	 */
	public static final AddressLayout pStdPictureInfo$layout()
	{
		return pStdPictureInfo$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const StdVideoDecodeH265PictureInfo *pStdPictureInfo
	 *}
	 */
	public static final long pStdPictureInfo$offset()
	{
		return pStdPictureInfo$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const StdVideoDecodeH265PictureInfo *pStdPictureInfo
	 *}
	 */
	public static MemorySegment pStdPictureInfo(MemorySegment struct)
	{
		return struct.get(pStdPictureInfo$LAYOUT, pStdPictureInfo$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const StdVideoDecodeH265PictureInfo *pStdPictureInfo
	 *}
	 */
	public static void pStdPictureInfo(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pStdPictureInfo$LAYOUT, pStdPictureInfo$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * uint32_t sliceSegmentCount
	 *}
	 */
	public static final OfInt sliceSegmentCount$layout()
	{
		return sliceSegmentCount$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * uint32_t sliceSegmentCount
	 *}
	 */
	public static final long sliceSegmentCount$offset()
	{
		return sliceSegmentCount$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * uint32_t sliceSegmentCount
	 *}
	 */
	public static int sliceSegmentCount(MemorySegment struct)
	{
		return struct.get(sliceSegmentCount$LAYOUT, sliceSegmentCount$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * uint32_t sliceSegmentCount
	 *}
	 */
	public static void sliceSegmentCount(MemorySegment struct, int fieldValue)
	{
		struct.set(sliceSegmentCount$LAYOUT, sliceSegmentCount$OFFSET, fieldValue);
	}

	/**
	 * Layout for field:
	 * {@snippet lang = c:
	 * const uint32_t *pSliceSegmentOffsets
	 *}
	 */
	public static final AddressLayout pSliceSegmentOffsets$layout()
	{
		return pSliceSegmentOffsets$LAYOUT;
	}

	/**
	 * Offset for field:
	 * {@snippet lang = c:
	 * const uint32_t *pSliceSegmentOffsets
	 *}
	 */
	public static final long pSliceSegmentOffsets$offset()
	{
		return pSliceSegmentOffsets$OFFSET;
	}

	/**
	 * Getter for field:
	 * {@snippet lang = c:
	 * const uint32_t *pSliceSegmentOffsets
	 *}
	 */
	public static MemorySegment pSliceSegmentOffsets(MemorySegment struct)
	{
		return struct.get(pSliceSegmentOffsets$LAYOUT, pSliceSegmentOffsets$OFFSET);
	}

	/**
	 * Setter for field:
	 * {@snippet lang = c:
	 * const uint32_t *pSliceSegmentOffsets
	 *}
	 */
	public static void pSliceSegmentOffsets(MemorySegment struct, MemorySegment fieldValue)
	{
		struct.set(pSliceSegmentOffsets$LAYOUT, pSliceSegmentOffsets$OFFSET, fieldValue);
	}

	/**
	 * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
	 * address {@code arrayParam.address() + index * layout().byteSize()}
	 */
	public static MemorySegment asSlice(MemorySegment array, long index)
	{
		return array.asSlice(layout().byteSize() * index);
	}

	/**
	 * The layout of this struct
	 */
	public static final GroupLayout layout()
	{
		return $LAYOUT;
	}

	/**
	 * The size (in bytes) of this struct
	 */
	public static long sizeof()
	{
		return layout().byteSize();
	}

	/**
	 * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
	 */
	public static MemorySegment allocate(SegmentAllocator allocator)
	{
		return allocator.allocate(layout());
	}

	/**
	 * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
	 * {@code elementCount * layout().byteSize()}.
	 */
	public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
	{
		return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
	{
		return reinterpret(addr, 1, arena, cleanup);
	}

	/**
	 * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
	 * size {@code elementCount * layout().byteSize()}
	 */
	public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
											Consumer<MemorySegment> cleanup)
	{
		return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
	}
}

